/**
 * 远古主题：新增事件。
 */
import type { AdventureEvent } from '../themes.js'

export const ANCIENT_NEW_EVENTS: readonly AdventureEvent[] = [
  { id: 'flint-spark', title: '燧石火花', description: '寒夜里，两块燧石在你手中擦出第一簇火苗。部落的孩子们围拢过来，火光映亮了一张张冻僵的脸。', effects: { intelligence: 3, luck: 1 }, exp: 10, weight: 1 },
  { id: 'bone-flute', title: '骨笛夜声', description: '拾到一支刻满孔洞的兽骨短笛，你试着吹响，竟引来了林间此起彼伏的回应。据说那是早已消失的「风语族」的遗物。', effects: { charisma: 3, intelligence: 2 }, exp: 11, weight: 1 },
  { id: 'clan-migration', title: '举族迁徙', description: '旱季逼着整个部落向西迁徙，你主动背起刚满月的兽皮襁褓。一路风沙，孩子们却渐渐只肯在你怀里入睡。', effects: { vitality: 3, charisma: 1 }, exp: 10, weight: 1 },
  { id: 'tide-crabs', title: '潮间拾贝', description: '退潮后的礁石缝里爬满拳头大的海蟹，你冒险探进湿滑的岩洞，摸到一串被海草裹住的远古贝壳项链。', effects: { agility: 3, luck: 2 }, exp: 12, weight: 1 },
  { id: 'sky-fire', title: '天火之夜', description: '一颗拖着长尾的「天火」坠落在远山，整夜天空泛着诡异的红光。长老说，先民曾在坠落之地挖出过会发光的石头。', effects: { intelligence: 3, luck: 2 }, exp: 12, weight: 1 },
  { id: 'wolf-howls', title: '狼群环伺', description: '篝火将熄，环伺的狼群在黑暗中亮起一双双绿眼。你抓起火把独自迎上前去，用一声长啸镇住了躁动的狼群。', effects: { charisma: 4, vitality: 1 }, exp: 13, weight: 1 },
  { id: 'clay-jar', title: '陶窑开火', description: '你照看了一整夜的陶窑终于出窑，釉面上浮现出连匠人都没见过的波浪纹。族长说，这是「河神」在借你的手作画。', effects: { intelligence: 2, luck: 2 }, exp: 10, weight: 1 },
  { id: 'wild-honey', title: '悬岩取蜜', description: '野蜂群在悬崖上筑起一座巨大的蜜巢，你腰系藤索悬在半空，用烟熏开蜂群，取回了整整一陶罐金黄的蜜。', effects: { agility: 4, vitality: 1 }, exp: 13, weight: 1 },
  { id: 'petrified-forest', title: '石化之林', description: '山腰有一片灰白的石化森林，树木保持着被瞬间冻结的姿态。你在林间找到一块刻着螺旋纹的树皮化石。', effects: { intelligence: 4, luck: 1 }, exp: 12, weight: 1 },
  { id: 'geyser-field', title: '喷泉谷地', description: '热泉谷每隔一刻钟便喷出滚烫的水柱，你踩着发烫的石板穿过谷地，顺手在泉眼旁捞出几颗温热的矿石。', effects: { vitality: 3, agility: 2 }, exp: 12, weight: 1 },
  { id: 'shadow-prowler', title: '暗影潜行', description: '夜巡时你察觉到身后若有若无的脚步声，屏息绕到岩壁后，看到一个披着兽皮的影子正悄悄模仿你的动作。', effects: { agility: 4, intelligence: 1 }, exp: 12, weight: 1 },
  { id: 'meadow-herbs', title: '草药寻踪', description: '巫医用枯枝在地上画出三种草药的形状，让你去北坡寻找。你翻遍石缝，竟在狼窝边找到了最难找的那株「月光草」。', effects: { intelligence: 3, vitality: 2 }, exp: 11, weight: 1 },
  { id: 'bone-games', title: '骨骰赌局', description: '营地的猎手们用打磨过的兽骨骰子赌明天的猎物，你随手一掷，竟摇出了几十年没出现过的「九兽纹」。', effects: { luck: 4, charisma: 1 }, exp: 11, weight: 1 },
  { id: 'ice-cave', title: '冰窟回声', description: '冰川深处传来若有若无的敲击声，你循声钻进冰窟，在冰壁上看到一幅被冻住的巨人足印，足印里嵌着一颗黑色晶石。', effects: { intelligence: 3, luck: 2 }, exp: 13, weight: 1 },
  { id: 'river-ford', title: '渡河之险', description: '春汛把独木桥冲得摇摇欲坠，你背起走不动的老人，在浮冰撞击声中一步一步蹚过了齐腰的河水。', effects: { strength: 3, charisma: 2 }, exp: 13, weight: 1 },
  { id: 'totem-carving', title: '图腾刻痕', description: '你奉命为新立的图腾柱补刻兽纹，一刀下去，刻痕里渗出的木汁竟带着淡淡的血腥气。老祭司盯着那纹路，良久不语。', effects: { strength: 2, luck: 2 }, exp: 10, weight: 1 },
  { id: 'thunder-storm', title: '雷暴之中', description: '雷暴撕裂夜空，一颗滚雷落在你三步之外，焦土上留下蛛网般的银纹。你捡起纹路中央那块滚烫的石片，指尖微麻。', effects: { luck: 3, vitality: 2 }, exp: 12, weight: 1 },
  { id: 'falcon-chick', title: '雏鹰坠巢', description: '暴风把一只雏鹰刮落悬崖，你攀着藤蔓把它送回鹰巢。母鹰盘旋三圈，从此总在部落上空为你领航。', effects: { charisma: 3, agility: 2 }, exp: 12, weight: 1 },
  { id: 'marsh-willow', title: '沼泽灯草', description: '沼泽深处浮着点点荧光，你蹚着没过膝盖的泥水靠近，发现是一丛会发光的灯草，根下缠着一块刻满楔形符号的石板。', effects: { intelligence: 4, agility: 1 }, exp: 12, weight: 1 },
  { id: 'ancient-mill', title: '石磨遗址', description: '密林里立着一座半塌的石磨，碾盘上残留着金色的粉末。你把粉末带回营地，巫医用它配成了能驱散兽群的气味粉。', effects: { intelligence: 3, luck: 1 }, exp: 10, weight: 1 },
  { id: 'bear-cub', title: '洞熊幼崽', description: '你在河滩捡到一只冻僵的洞熊幼崽，母熊的足迹就在不远处。你犹豫片刻，把幼崽放回足迹旁，转身时听见一声低沉的哼鸣。', effects: { charisma: 3, luck: 2 }, exp: 11, weight: 1 },
  { id: 'star-fall', title: '星坠之湖', description: '夜半，一颗流星坠入部落北面的湖心，湖水一夜之间变得温热。你潜入湖底，摸到一块仍在发光的星核碎片。', effects: { luck: 4, vitality: 2 }, exp: 13, weight: 1 },
  { id: 'barter-fair', title: '以物易物', description: '游商部落带来了盐、铜片和会唱歌的骨匣。你用手工打磨的玉石，换到了那把削骨如泥的铜片刀，猎手们羡慕得直咂嘴。', effects: { charisma: 3, intelligence: 2 }, exp: 11, weight: 1 },
  { id: 'cave-echo', title: '回声探路', description: '陌生的溶洞里伸手不见五指，你靠敲击石壁的回声判断方向，竟跌跌撞撞走出了一条连老猎手都没走过的路。', effects: { intelligence: 4, agility: 1 }, exp: 12, weight: 1 },
  { id: 'obsidian-knife', title: '黑曜石刃', description: '你在火山脚下发现一片黑曜石碎屑，顺藤摸瓜找到一块完美的黑曜石原石。石刃打磨成型后，削骨如泥。', effects: { strength: 3, agility: 1 }, exp: 10, weight: 1 },
  { id: 'turtle-shell', title: '巨龟驮行', description: '一头小山般的巨龟缓缓爬过河滩，背上驮着青苔与野花。你攀上龟背搭了一程顺风路，龟甲上还留着先民刻的地图。', effects: { luck: 3, intelligence: 1 }, exp: 10, weight: 1 },
  { id: 'moon-plant', title: '月下花语', description: '满月之夜，谷地里的银瓣花齐齐绽放，花蕊朝向月亮轻轻摇摆。你在花丛中央看到一株开着双色花苞的异株。', effects: { luck: 3, charisma: 2 }, exp: 11, weight: 1 },
  { id: 'drum-call', title: '兽皮鼓点', description: '暮色里，部落的兽皮鼓声由缓转急，你跟着鼓点加入围火之舞。老鼓手把鼓槌塞进你手里，说你的节奏里有「山的心跳」。', effects: { charisma: 3, vitality: 2 }, exp: 11, weight: 1 },
  { id: 'sand-burial', title: '沙暴埋骨', description: '沙暴过后，干涸的河床上露出一具裹着兽皮的枯骨，手中紧握一根刻满符文的骨杖。你按部落礼数将它重新掩埋。', effects: { luck: 3, intelligence: 2 }, exp: 12, weight: 1 },
  { id: 'heron-guide', title: '白鹭引路', description: '一群白鹭忽然在你头顶盘旋三圈，向雾谷深处飞去。你跟上去，在雾气散开的瞬间看见一片从未有人踏足的石林。', effects: { luck: 3, agility: 2 }, exp: 12, weight: 1 },
  { id: 'fire-watch', title: '守夜人', description: '轮到你守夜，寒霜爬满睫毛。黎明前最黑的一刻，你听见篝火「噼啪」一声，火舌里竟浮出一张微笑的脸。', effects: { vitality: 3, charisma: 1 }, exp: 10, weight: 1 },
  { id: 'root-cellar', title: '树根地窖', description: '千年古树的树根下塌出一个地窖，里面整齐码着几罐发黑的种子。你种下几粒，三个月后长出了穗子泛金光的作物。', effects: { intelligence: 3, luck: 2 }, exp: 12, weight: 1 },
  { id: 'mountain-echo', title: '山呼谷应', description: '你朝群山喊出自己的名字，回声在谷间层层叠叠地回荡，最后一声竟变了调，像某个古老的名字在应答。', effects: { charisma: 3, luck: 1 }, exp: 10, weight: 1 },
  { id: 'honey-dew', title: '蜜露晨光', description: '清晨的草叶上凝着甜腻的蜜露，据说那是「天河」洒下的口水。你舔了舔，一整天都觉得脚步轻快。', effects: { vitality: 3, luck: 1 }, exp: 9, weight: 1 },
  { id: 'broken-spear', title: '断矛重铸', description: '猎队折断了最趁手的那杆石矛，你连夜到河滩拣选燧石，用兽筋重新绑扎。新矛投出去时，稳稳钉进了百步外的树干。', effects: { strength: 3, agility: 1 }, exp: 10, weight: 1 },
  { id: 'ghost-fire', title: '磷火引路', description: '夜行迷路时，几点幽蓝的磷火在密林间浮动。你壮着胆子跟上，竟被引到了一处涌着甜水的泉眼旁。', effects: { luck: 3, vitality: 1 }, exp: 10, weight: 1 },
  { id: 'pigment-cave', title: '赭石颜料', description: '你在崖壁夹缝里发现整层赭石与白垩，调配出的颜料让部落画师惊叹。第一幅壁画完成时，你也在上面按下了手印。', effects: { charisma: 2, intelligence: 2 }, exp: 10, weight: 1 },
  { id: 'frost-morning', title: '霜晨脚印', description: '雪地上有一串比人脚大两倍的脚印，延伸到悬崖边就消失了。你顺着脚印找到一窝被冻住的蛋，蛋壳上泛着金属光泽。', effects: { intelligence: 3, luck: 2 }, exp: 12, weight: 1 },
  { id: 'driftwood-boat', title: '浮木之舟', description: '你扎的浮木筏刚下水，就被暗流卷进一处水下溶洞。你屏住呼吸钻出来时，头顶是满天繁星，眼前是一座半沉的石殿。', effects: { agility: 3, luck: 2 }, exp: 13, weight: 1 },
  { id: 'winter-store', title: '冬藏之仓', description: '部落的储粮仓被地鼠啃出了大洞，你蹲守三天摸清鼠道，用烟熏加围堵一夜清剿。族长破例让你先取一份口粮。', effects: { intelligence: 3, agility: 1 }, exp: 10, weight: 1 },
  { id: 'voice-imitation', title: '兽语模仿', description: '你蹲在灌木后模仿鹿鸣，竟引来了真正的鹿群。猎手们说，部落里上一个能「和兽说话」的人，是传说里的那位半神。', effects: { charisma: 3, agility: 2 }, exp: 12, weight: 1 },
  { id: 'volcanic-garden', title: '火山热土', description: '火山灰覆盖的山坡上冒出新绿，你随手插下的枝条几天就扎了根。长老说，这是「地火」苏醒的征兆，也是丰年的吉兆。', effects: { vitality: 3, luck: 2 }, exp: 11, weight: 1 },
  { id: 'moonstone-cave', title: '月光石洞', description: '深夜，你偶然走进一座山洞，洞壁上的矿石竟泛起柔和的银光，仿佛整座山洞都在呼吸。你在最亮的石壁上抠出一粒温润的月光石。', effects: { luck: 4, charisma: 1 }, exp: 12, weight: 1 },
  { id: 'weaving-loom', title: '织网手艺', description: '你用兽筋和苇草织出一张比麻绳更结实的渔网，第一网就捞上来一条从未见过的银鳞怪鱼，鱼腹里滚出一颗圆润的珠子。', effects: { intelligence: 2, luck: 3 }, exp: 11, weight: 1 },
  { id: 'eclipse-omen', title: '天狗食日', description: '日食降临，天地陷入诡异的昏暗，部落陷入恐慌。你举起火把站在高台上，用一句话稳住了所有人的心。', effects: { charisma: 4, intelligence: 1 }, exp: 12, weight: 1 },
  { id: 'salt-march', title: '运盐古道', description: '你随商队穿越盐碱滩，闷热的空气里飘着咸腥味。你发现一条被风沙掩埋的旧道，沿路捡到几块刻着车轮纹的陶片。', effects: { vitality: 3, agility: 1 }, exp: 10, weight: 1 },
  { id: 'nest-eggs', title: '鹰巢偷蛋', description: '为给生病的幼童补身子，你攀上鹰巢取蛋，被归巢的巨鹰追了三座山头。蛋平安送到，你的背上也多了一道爪痕。', effects: { agility: 4, charisma: 1 }, exp: 13, weight: 1 },
  { id: 'mud-spring', title: '泥泉滚烫', description: '你误踩进一处滚烫的泥泉，烫得直跳脚，却意外发现泉底铺着一层细腻的黏土——正好是烧制陶器的上等原料。', effects: { vitality: -2, intelligence: 3 }, exp: 11, weight: 1 },
  { id: 'poison-fog', title: '毒瘴横渡', description: '雾谷的瘴气一夜之间变浓，你屏息穿过时仍吸进几口，头晕目眩，但你在谷底捡到了猎人梦寐以求的「解毒草」。', effects: { vitality: -2, agility: 3 }, exp: 12, weight: 1 },
  { id: 'nightmare-bite', title: '梦魇缠身', description: '你连着三夜梦见自己沉入无光的深海，醒来时浑身冷汗。但那些梦里的碎片，竟让你读懂了祭坛符文的一角。', effects: { luck: -2, intelligence: 4 }, exp: 13, weight: 1 },
  { id: 'antler-shed', title: '鹿角易主', description: '你捡到一对完美脱落的鹿角，却被年轻猎手当众指责是「偷来的」。你当场比试箭术自证，赢得干净利落。', effects: { charisma: -1, agility: 4 }, exp: 12, weight: 1 },
  { id: 'snow-blind', title: '雪盲之险', description: '暴雪里你为找回走失的羊羔在山脊上摸索了一夜，眼睛被雪光刺得通红。所幸羊羔安然无恙，你也记住了那条冰缝的位置。', effects: { vitality: -1, strength: 3 }, exp: 11, weight: 1 },
  { id: 'river-pearl', title: '河蚌探珠', description: '你潜入冰冷的河底摸河蚌，冻得嘴唇发紫，却在最大的那只蚌里摸到一颗滚圆的黑珍珠。巫医说它能避邪。', effects: { vitality: -1, luck: 4 }, exp: 12, weight: 1 },
  { id: 'thunder-tree', title: '雷击神木', description: '雷劈中了部落奉为神明的古树，树心裂开，露出一个焦黑的空洞。你钻进去，在灰烬里找到一截仍带着电光的枝芯。', effects: { luck: 2, vitality: 2 }, exp: 13, weight: 1 },
  { id: 'whale-bone', title: '巨鲸骸骨', description: '退潮的滩涂上躺着一具搁浅巨鲸的骸骨，肋骨折断处嵌着石斧的痕迹。你顺着肋骨爬上鲸背，望见了从未见过的海平线。', effects: { strength: 2, intelligence: 2 }, exp: 11, weight: 1 },
  { id: 'spear-duel', title: '矛尖对决', description: '邻族猎手上门挑战，要与你以石矛一决高下。围观者围成圆圈，鼓声擂动，胜者将赢得两族共猎的权利。', effects: { strength: 4, agility: 3 }, exp: 15, minLevel: 2, weight: 1 },
  { id: 'spirit-mask', title: '神巫之面', description: '部落的祭仪之夜，老神巫把一张开裂的木面具递到你面前，要你替她主持今年的「唤灵之舞」。', effects: { charisma: 4, luck: 3 }, exp: 15, minLevel: 2, weight: 1 },
  { id: 'canyon-bridge', title: '峡谷索道', description: '两座断崖之间只剩一道摇摇欲坠的藤桥，桥下是翻涌的雾海。要护送药草到对岸，你只有一炷香的时间。', effects: { agility: 5, strength: 2 }, exp: 15, minLevel: 2, weight: 1 },
  { id: 'rhino-mud', title: '陷泥犀牛', description: '一头小山般的巨角犀牛陷进泥潭，挣扎着越陷越深。你指挥族人搭起木架，花了一整天把巨兽从泥里拉了出来。', effects: { strength: 4, charisma: 2 }, exp: 15, minLevel: 2, weight: 1 },
  { id: 'deep-shaft', title: '深井坠物', description: '一口竖井深不见底，井壁刻满螺旋纹路。部落最亮的火把被风吹落井中，你系绳而下，在井底看见一扇紧闭的石门。', effects: { intelligence: 4, luck: 3 }, exp: 16, minLevel: 2, weight: 1 },
  { id: 'blizzard-hunt', title: '暴雪猎踪', description: '暴雪封山，猎物一夜消失。你循着雪地上微弱的血痕追踪三天，终于在山洞深处堵住了一头受伤的雪原巨熊。', effects: { agility: 4, strength: 3 }, exp: 16, minLevel: 2, weight: 1 },
  { id: 'sun-dial', title: '日晷之约', description: '石阵中央的日晷投下奇怪的影子，指向一道从未开启的石缝。族人们都说，那是先祖留下的「时间之门」。', effects: { intelligence: 5, luck: 2 }, exp: 16, minLevel: 2, weight: 1 },
  { id: 'war-drum', title: '战鼓之争', description: '两大部落为一片猎场剑拔弩张，酋长让你作为使者去谈判。你带着一张兽皮地图，独自走进了对方的帐篷。', effects: { charisma: 5, intelligence: 2 }, exp: 15, minLevel: 2, weight: 1 },
  { id: 'fire-races', title: '火种接力', description: '部落的火种在暴风雨中熄灭，你带人冒雨攀上雷击峰，在焦木深处重新引燃了火种，一路护送回营地。', effects: { vitality: 4, strength: 3 }, exp: 16, minLevel: 2, weight: 1 },
  { id: 'shadow-cave', title: '影窟之物', description: '猎人传说影窟里住着「无面之物」，进去的人都会忘记回家的路。你为寻回失踪的同伴，点燃火把走了进去。', effects: { intelligence: 4, agility: 3 }, exp: 16, minLevel: 2, weight: 1 },
  { id: 'whale-song', title: '鲸歌引航', description: '海岸边传来低沉的鲸歌，渔人们说那是「海神」的召唤。你乘独木舟循声而去，在雾中看见一头银白色的巨鲸浮出水面。', effects: { luck: 4, vitality: 3 }, exp: 15, minLevel: 2, weight: 1 },
  { id: 'totem-trial', title: '图腾试炼', description: '部族祭师宣布，下一个图腾守护者将从年轻一代中选出。考验很简单：在兽骨图腾下独自守满三天三夜。', effects: { strength: 3, vitality: 4 }, exp: 16, minLevel: 2, weight: 1 },
  { id: 'ancient-road', title: '古道遗迹', description: '密林里露出一段铺着石板的老路，路尽头立着一根半塌的石柱。你顺着石柱指印的方向，找到了一座掩埋千年的粮仓。', effects: { intelligence: 4, luck: 2 }, exp: 15, minLevel: 2, weight: 1 },
  { id: 'eagle-flight', title: '鹰背之约', description: '你救过的那只巨鹰盘旋落下，用翅膀轻推你的背。你壮着胆子爬上鹰背，它载着你掠过云海，落在了一座悬浮的石台上。', effects: { agility: 5, charisma: 2 }, exp: 17, minLevel: 2, weight: 1 },
  { id: 'sunken-temple', title: '水下沉殿', description: '你屏息潜入湖底，发现一座保存完好的水下沉殿，殿门上的浮雕描绘着「水神」与「火神」的决战。', effects: { intelligence: 5, luck: 3 }, exp: 17, minLevel: 3, weight: 1 },
  { id: 'glacier-giant', title: '冰原巨灵', description: '冰原深处，一个由寒冰凝成的巨影缓缓站起，胸口封着一块跳动的蓝光。它向你伸出手掌，仿佛在等什么。', effects: { strength: 5, vitality: 3 }, exp: 17, minLevel: 3, weight: 1 },
  { id: 'tribe-council', title: '部落之议', description: '饥荒之年，各氏族在篝火边争论迁徙方向，吵得不可开交。你站起来，用一张炭画地图平息了所有争执。', effects: { charisma: 5, intelligence: 3 }, exp: 16, minLevel: 3, weight: 1 },
  { id: 'underground-river', title: '地下暗河', description: '你顺着溶洞里的暗河漂流了整整一天，河水时而湍急时而平静，最后把你冲进一片发着幽光的地下森林。', effects: { agility: 4, luck: 4 }, exp: 17, minLevel: 3, weight: 1 },
  { id: 'feather-omen', title: '羽翎占卜', description: '神巫抛出一把兽骨与羽毛，落地时羽毛竟悬在半空不落。她说这是百年一遇的「神启之兆」，要你随她走一趟雾谷。', effects: { luck: 5, intelligence: 2 }, exp: 17, minLevel: 3, weight: 1 },
  { id: 'broken-sword', title: '断剑之锋', description: '猎队挖出一截锈迹斑斑的青铜断剑，剑身上刻着看不懂的文字。你磨去锈迹，剑锋在月光下竟泛起寒光。', effects: { strength: 4, intelligence: 3 }, exp: 16, minLevel: 3, weight: 1 },
  { id: 'wolf-king', title: '狼王对视', description: '你独自在雪原上与狼王狭路相逢，它体型如山，银白的鬃毛在风里猎猎作响。它没有扑向你，只是与你对视良久。', effects: { charisma: 4, strength: 3 }, exp: 16, minLevel: 3, weight: 1 },
  { id: 'storm-ritual', title: '祈雨之舞', description: '连月大旱，部落推举你在祭坛上领跳祈雨之舞。你跳到第七圈时，第一滴雨落在了你的眉心。', effects: { charisma: 4, luck: 3 }, exp: 16, minLevel: 3, weight: 1 },
  { id: 'crystal-cave', title: '晶石矿脉', description: '你发现一条隐秘的水晶矿脉，晶体在火把下折射出七彩的光。族人说，这足够换回部落三年都用不完的盐。', effects: { intelligence: 4, luck: 3 }, exp: 16, minLevel: 3, weight: 1 },
  { id: 'saurian-eggs', title: '恐兽巢穴', description: '你在巨兽巢穴附近发现几枚带花纹的巨蛋，母兽正在附近巡视。你小心翼翼绕开它，把蛋的图案记在了兽皮上。', effects: { agility: 5, intelligence: 2 }, exp: 16, minLevel: 3, weight: 1 },
  { id: 'river-god', title: '河神之礼', description: '你在祭河仪式上投入贡品，河水却突然倒流，把一件青铜面具冲到你脚边。巫医说，这是河神收下了你的诚意。', effects: { luck: 5, charisma: 2 }, exp: 17, minLevel: 3, weight: 1 },
  { id: 'echo-mountain', title: '回声之山', description: '传说回声之山的山腹里藏着一面「通神之鼓」。你循着山体里传来的鼓声攀登，在崖壁上发现了一排上古的踏脚石。', effects: { strength: 4, agility: 4 }, exp: 17, minLevel: 3, weight: 1 },
  { id: 'night-sun', title: '极昼之谜', description: '盛夏的北地，太阳整夜不落，兽群躁动不安。长老说，这是「天穹之眼」睁开的时候，也是先祖英灵回家的季节。', effects: { intelligence: 4, vitality: 3 }, exp: 16, minLevel: 3, weight: 1 },
  { id: 'sleeping-god', title: '沉睡山神', description: '地震惊醒了沉睡万年的山神，它从裂开的山脊中缓缓坐起，声音像雷鸣：「谁扰了我的长眠？」', effects: { vitality: 5, luck: 3 }, exp: 20, minLevel: 4, weight: 1 },
  { id: 'stone-army', title: '石兵阵列', description: '月食之夜，埋在地下的石兵像活过来一样列成阵列，齐刷刷望向部落的方向。阵眼处，一个石雕将军缓缓举起了剑。', effects: { strength: 5, intelligence: 4 }, exp: 21, minLevel: 4, weight: 1 },
  { id: 'primordial-beast', title: '洪荒巨兽', description: '沉睡在冰层下的洪荒巨兽苏醒，一吼震裂千里冰原。各部族合力布下陷阱，而你被推举为引它入阵的诱饵。', effects: { agility: 5, vitality: 4 }, exp: 22, minLevel: 4, weight: 1 },
  { id: 'sky-whale', title: '天穹巨鲸', description: '一头山岳般巨大的天穹巨鲸掠过云海，洒下的水雾化作彩虹。它在你头顶盘旋三圈，仿佛在辨认你是不是故人。', effects: { luck: 5, charisma: 4 }, exp: 23, minLevel: 5, weight: 1 },
  { id: 'sun-temple', title: '太阳神殿', description: '你在沙漠深处找到传说中的太阳神殿，殿门只有正午时分的阳光才能照开。门后，是失落文明留下的第一手记载。', effects: { intelligence: 6, luck: 3 }, exp: 22, minLevel: 5, weight: 1 },
  { id: 'world-tree', title: '世界之树', description: '传说撑起天地的世界之树在你面前显形，树冠托着星河，根系深入九幽。它的一片叶子落下来，轻轻停在你的肩头。', effects: { vitality: 5, luck: 4 }, exp: 23, minLevel: 5, weight: 1 },
  { id: 'first-dawn', title: '初曦之刻', description: '你被卷入时间回流的漩涡，亲眼目睹第一缕晨曦撕裂混沌的那一刻。创世的光落在你身上，也在你体内刻下了法则的烙印。', effects: { intelligence: 6, vitality: 5 }, exp: 26, minLevel: 6, weight: 1 },
]
