/**
 * 动漫主题：新增事件。
 */
import type { AdventureEvent } from '../themes.js'

export const ANIME_NEW_EVENTS: readonly AdventureEvent[] = [
  // ===== 日常（55 个，无 minLevel）=====
  { id: 'morning-run', title: '晨跑偶遇', description: '清晨跑步时，总在同一个路口遇到一位白发老人。他教你调整呼吸的节奏，说这是五十年前教练传给他的秘诀。', effects: { agility: 2, vitality: 1 }, exp: 10, weight: 1 },
  { id: 'desk-note', title: '讲台遗物', description: '放学值日时，你在讲台抽屉深处发现一本泛黄的笔记本，扉页写着「毕业那天，把它交给下一个有缘人」。', effects: { intelligence: 3 }, exp: 11, weight: 1 },
  { id: 'lunch-bento', title: '便当之谜', description: '午休打开便当，里面多了一双筷子，还有张字条写着「注意营养均衡」。同桌红着脸假装在看窗外。', effects: { charisma: 3, luck: 1 }, exp: 11, weight: 1 },
  { id: 'rooftop-wind', title: '天台的风', description: '天台的风把作业本吹得满天飞，路过的老师帮你追回三页，还顺手指出了你犯的两处计算错误。', effects: { intelligence: 2, luck: 1 }, exp: 10, weight: 1 },
  { id: 'manga-shelving', title: '漫画整理', description: '在漫画店打工的你发现整套热门连载被摆错了顺序，强迫症发作的你把它们一一归位，店长默默给你加了工时。', effects: { intelligence: 2, agility: 1 }, exp: 10, weight: 1 },
  { id: 'midnight-practice', title: '中二台词', description: '深夜你对着镜子练习必杀技的释放台词，中二之魂熊熊燃烧。隔壁阳台传来一句「我也要喊」，你们隔空对上了暗号。', effects: { charisma: 2, vitality: 1 }, exp: 10, weight: 1 },
  { id: 'discount-bread', title: '最后的面包', description: '便利店打折区的货架上只剩最后一个菠萝包，你一个箭步抢到，收银台前排队的上班族投来幽怨的目光。', effects: { luck: 3 }, exp: 9, weight: 1 },
  { id: 'star-patch', title: '星星补丁', description: '校服袖口磨破的第二天，你发现上面多了一枚手缝的星星补丁，针脚细密，一看就是老妈熬夜缝的。', effects: { charisma: 1, vitality: 2 }, exp: 10, weight: 1 },
  { id: 'corridor-sprint', title: '走廊冲刺', description: '上课铃响的前一秒，你抱着课本在走廊里全速冲刺，在转角处与教导主任擦肩而过，他的假发被气流掀起了一角。', effects: { agility: 3 }, exp: 10, weight: 1 },
  { id: 'homework-deal', title: '作业外交', description: '你把整理好的笔记借给慌乱的同桌，换来了他珍藏的限量手办情报——原来他叔叔是模型店的店长。', effects: { charisma: 2, intelligence: 1 }, exp: 11, weight: 1 },
  { id: 'vending-windfall', title: '多出的饮料', description: '自动贩卖机多吐出一罐果汁，你犹豫再三还是拿了。后来才想起，刚才排在后面的大叔好像就少了一罐。', effects: { luck: 2, charisma: -1 }, exp: 10, weight: 1 },
  { id: 'bus-seat', title: '电车让座', description: '拥挤的电车上你给一位老奶奶让座，她笑着塞给你一颗奶糖，说是她孙子最爱吃的牌子。', effects: { charisma: 3 }, exp: 10, weight: 1 },
  { id: 'cold-medicine', title: '感冒药', description: '你感冒的那天，同桌没说话，只是把药和热水放在你桌上，杯壁上贴着一张便利贴：「喝完记得打篮球」。', effects: { vitality: 2, charisma: 1 }, exp: 11, weight: 1 },
  { id: 'broadcast-stand', title: '临时主播', description: '晨间广播的主播临时缺席，你被赶鸭子上架念了一篇鸡汤稿，全校师生都记住了你略带颤抖的声音。', effects: { charisma: 3, luck: 1 }, exp: 11, weight: 1 },
  { id: 'lost-key', title: '忘带的钥匙', description: '放学后你发现自己把钥匙忘在了教室，只好学电视剧里那样翻窗而入，被路过的保安大叔看个正着，他居然给你鼓掌。', effects: { agility: 2, luck: 1 }, exp: 10, weight: 1 },
  { id: 'ramen-egg', title: '深夜加蛋', description: '深夜煮泡面时，冰箱里恰好还剩最后一颗蛋，你郑重其事地把它煎成溏心蛋，仪式感拉满。', effects: { vitality: 2, luck: 1 }, exp: 10, weight: 1 },
  { id: 'club-ledger', title: '社团账本', description: '帮社团整理账目时，你发现三年前有一笔会费被重复记了两遍，查清后社团经费一下子宽裕起来，部长激动得把你举了起来。', effects: { intelligence: 3 }, exp: 12, weight: 1 },
  { id: 'relay-race', title: '最后一棒', description: '体育课的接力赛上，你接过最后一棒时已经落后半个操场，你咬牙提速，居然追平了纪录。', effects: { agility: 3, vitality: 1 }, exp: 12, weight: 1 },
  { id: 'blackboard-art', title: '黑板报', description: '放学后你留下来画文化祭的黑板报，粉笔灰落了一身，画完时月光正好从窗户斜斜照进来。', effects: { charisma: 2, intelligence: 1 }, exp: 11, weight: 1 },
  { id: 'shared-umbrella', title: '雨中共伞', description: '突如其来的暴雨里，你与一个陌生女孩共撑一把伞走到车站，她下车前说了句「谢谢」，声音轻得像雨点。', effects: { charisma: 2, luck: 1 }, exp: 11, weight: 1 },
  { id: 'old-comic', title: '绝版漫画', description: '旧书摊上你淘到一本绝版漫画，老板眯着眼说这书他留了十年，就等一个识货的人。', effects: { luck: 3, intelligence: 1 }, exp: 11, weight: 1 },
  { id: 'line-rehearsal', title: '台词被录', description: '你对着镜子练习主角台词到忘我，却听见妹妹的房门后传来一声憋笑的录音键音，她手上多了一份「黑历史」。', effects: { charisma: 2, luck: -1 }, exp: 10, weight: 1 },
  { id: 'convenience-shift', title: '深夜打工', description: '深夜便利店的打工时间，一位总买关东煮的常客忽然问你：「你觉得这个世界会被外星人统治吗？」你认真思考了十分钟。', effects: { intelligence: 2, charisma: 1 }, exp: 11, weight: 1 },
  { id: 'library-close', title: '闭馆留客', description: '图书馆闭馆的铃声响起，管理员见你正读到高潮处，破例让你多看了半小时，还悄悄帮你留了盏灯。', effects: { intelligence: 2, luck: 1 }, exp: 10, weight: 1 },
  { id: 'canteen-scoop', title: '阿姨的手', description: '食堂阿姨给你打菜时手抖了一下，抖出来的却是满满一勺红烧肉，她眨眨眼，示意你别说出去。', effects: { vitality: 2, charisma: 1 }, exp: 10, weight: 1 },
  { id: 'rain-soaked-hw', title: '淋湿的作业', description: '作业本被突如其来的大雨淋成了纸浆，你熬夜重写了一遍，意外发现重写时记得比原来牢得多。', effects: { intelligence: 2, vitality: -1 }, exp: 12, weight: 1 },
  { id: 'cat-guide', title: '猫之领路', description: '上学路上，一只橘猫忽然拦住你的去路，非要领着你绕远路。你跟着它穿过小巷，才发现前面的大路塌方了。', effects: { luck: 3 }, exp: 12, weight: 1 },
  { id: 'lost-freshman', title: '迷路的新生', description: '你帮一个迷路的新生指路，他激动得差点原地转圈，末了塞给你一张游戏厅的代金券，说是谢礼。', effects: { charisma: 2, luck: 1 }, exp: 10, weight: 1 },
  { id: 'signed-ball', title: '签名篮球', description: '整理体育仓库时，你在角落找到一颗落满灰的篮球，上面有一串龙飞凤舞的签名——是传说中毕业十年的传奇队长。', effects: { luck: 2, agility: 1 }, exp: 11, weight: 1 },
  { id: 'midnight-phone', title: '半夜求助', description: '凌晨一点，睡眼惺忪的你接到同学电话，对方带着哭腔问最后一题的答案。你口齿不清地报完，倒头又睡。', effects: { intelligence: 2, charisma: 1 }, exp: 10, weight: 1 },
  { id: 'riverside-yell', title: '河边呐喊', description: '清晨的河边，你迎着朝阳大喊出准备好的主角台词，惊起一群白鹭，也惊醒了岸边钓鱼的老大爷。', effects: { vitality: 2, charisma: 1 }, exp: 10, weight: 1 },
  { id: 'comic-petition', title: '联名请愿', description: '你最喜欢的漫画角色下周疑似要退场，你连夜发起联名请愿，短短一天就攒了三百个签名。', effects: { charisma: 3 }, exp: 11, weight: 1 },
  { id: 'duty-dodge', title: '值周放水', description: '值周检查时你放过了迟到的死党，他第二天提着一杯奶茶来「谢罪」，你却总觉得哪里不太对。', effects: { charisma: 2, luck: 1 }, exp: 10, weight: 1 },
  { id: 'rope-skipping', title: '跳绳纪录', description: '课间的跳绳大赛上，你鬼使神差地连跳了两百个，破了班级保持了五年的纪录，全班都围过来看。', effects: { agility: 3, vitality: 1 }, exp: 11, weight: 1 },
  { id: 'yearbook-dream', title: '旧毕业册', description: '翻箱倒柜时你找到了小学毕业册，上面写着「我长大要成为拯救世界的英雄」——你盯着这行字看了很久。', effects: { luck: 2, charisma: 1 }, exp: 11, weight: 1 },
  { id: 'breakfast-favor', title: '多送油条', description: '早餐摊老板娘多送你一根油条，说你埋头啃包子的样子像极了她在外地读书的儿子。', effects: { vitality: 2, charisma: 1 }, exp: 10, weight: 1 },
  { id: 'lucky-question', title: '恰好复习', description: '老师毫无预兆地点名提问，恰好是你昨晚睡前翻过的那个知识点，你答得行云流水，全班掌声雷动。', effects: { intelligence: 2, luck: 1 }, exp: 11, weight: 1 },
  { id: 'swept-coin', title: '扫出的硬币', description: '大扫除时你从墙角扫出一枚硬币，正面朝上。你捡起来擦了擦，决定把它当成今天的幸运符。', effects: { luck: 2 }, exp: 9, weight: 1 },
  { id: 'tennis-hit', title: '飞来的球', description: '路过网球场时你被一记飞球砸中后脑勺，捂着脑袋的你却因此认识了暴躁的网球部部长，他非要请你喝汽水赔罪。', effects: { charisma: 2, vitality: -1 }, exp: 10, weight: 1 },
  { id: 'bento-contest', title: '便当大赛', description: '学校突发奇想举办便当大赛，你凭一盒焦边但香气扑鼻的煎蛋卷意外夺冠，评委说「有种家庭的味道」。', effects: { charisma: 2, luck: 1 }, exp: 11, weight: 1 },
  { id: 'star-watching', title: '第一次木星', description: '天文部的同学把望远镜借给你，你第一次亲眼看到木星的条纹和它的小卫星，那种震撼让你愣了很久。', effects: { intelligence: 2 }, exp: 10, weight: 1 },
  { id: 'planner-check', title: '手账成真', description: '你翻出三个月前认真写下的手账，逐条对照——那些「想要做到」的事，竟然大部分都实现了。', effects: { intelligence: 2, luck: 1 }, exp: 11, weight: 1 },
  { id: 'mom-note', title: '便当纸条', description: '老妈的便当盒里多了一张纸条：「今天也要加油，别饿着。」你默默把纸条收进胸前的口袋里。', effects: { vitality: 2, charisma: 1 }, exp: 10, weight: 1 },
  { id: 'wrong-word', title: '念错的单词', description: '晨读时你把一个单词念得惊天动地，全班笑成一团。但那个单词，你这辈子都不会再念错了。', effects: { intelligence: 2, charisma: -1 }, exp: 11, weight: 1 },
  { id: 'bike-chain', title: '修车学徒', description: '自行车链掉在半路，你蹲在路边折腾了半小时，满手油污地把它装了回去，从此学会了这门手艺。', effects: { agility: 2, intelligence: 1 }, exp: 10, weight: 1 },
  { id: 'old-console', title: '童年存档', description: '你翻出积灰的游戏机，当年卡了一年的最终关卡，如今十分钟就打通了。你对着屏幕笑了笑，像在和十年前的自己击掌。', effects: { agility: 2, luck: 1 }, exp: 11, weight: 1 },
  { id: 'sudden-rain', title: '雨中的店', description: '说好的晴天忽然转雨，没带伞的你冲进一家小店躲雨，意外发现这是家超好吃的甜品店，老板还请你试吃新品。', effects: { luck: 3 }, exp: 11, weight: 1 },
  { id: 'proposal-plan', title: '策划书', description: '冷门社团迟迟找不到顾问老师，你花了一晚上写了份漂亮的策划书，第二天校长亲自过目，当场批了活动经费。', effects: { intelligence: 3, charisma: 1 }, exp: 12, weight: 1 },
  { id: 'elevator-out', title: '停运电梯', description: '电梯故障停运，你哼哧哼哧爬了十层楼梯，到顶时意外觉得神清气爽，连下午的课都精神了。', effects: { vitality: 3 }, exp: 10, weight: 1 },
  { id: 'goldfish-stall', title: '捞金鱼', description: '夜市捞金鱼的摊主夸你手法稳，破例让你多捞一条。你捧着三条金鱼回家，一路上小心得像捧着宝物。', effects: { agility: 2, luck: 1 }, exp: 10, weight: 1 },
  { id: 'note-exchange', title: '笔记回礼', description: '你把写得工整的笔记借给低年级的学妹，她第二天回赠了一份手写的学习心得，字迹漂亮得让你自愧不如。', effects: { charisma: 2, intelligence: 1 }, exp: 10, weight: 1 },
  { id: 'same-name', title: '同名主角', description: '新番预告里出现一个主角，居然和你同名同姓，连发型都像。你盯着屏幕，忽然有一种被选中的错觉。', effects: { luck: 3 }, exp: 11, weight: 1 },
  { id: 'seat-change', title: '幽灵学霸', description: '换座位后，你的新同桌是传说中从不说话的「幽灵学霸」。他第一次开口，居然是问你借橡皮。', effects: { intelligence: 2, luck: 1 }, exp: 11, weight: 1 },
  { id: 'lucky-draw', title: '再来一瓶', description: '便利店门口的抽奖箱里，你随手一抽就中了「再来一瓶」，店员姐姐笑着说你手气真好。', effects: { luck: 3 }, exp: 9, weight: 1 },
  { id: 'balcony-yell', title: '阳台晨练', description: '清晨在阳台晨练的你放声喊口号，楼下邻居家的柴犬跟着你一起汪汪叫，一人一狗竟意外合拍。', effects: { vitality: 2, charisma: -1 }, exp: 10, weight: 1 },
  // ===== 冒险（26 个，minLevel 2/3）=====
  { id: 'transfer-genius', title: '天才转校生', description: '新来的转校生是传说中的「天才」，入学第一天就放出豪言：「这个学校，只有你有资格当我的对手。」全班的目光齐刷刷落在你身上。', effects: { charisma: 3, strength: 2 }, exp: 14, minLevel: 2, weight: 1 },
  { id: 'camp-horror', title: '合宿试胆', description: '社团合宿第一天就遇上暴雨，你们被困在旧校舍，不知谁提议来一场试胆大会。手电筒的光圈里，似乎有什么在动。', effects: { agility: 3, luck: 1 }, exp: 14, minLevel: 2, weight: 1 },
  { id: 'street-fight', title: '街头挑衅', description: '放学路上，几个混混拦住你索要「保护费」。你深吸一口气，把书包递给身后的同伴，转身站定。', effects: { strength: 3, vitality: 2 }, exp: 15, minLevel: 2, weight: 1 },
  { id: 'locker-escape', title: '仓库密室', description: '你被人恶作剧锁进了体育仓库，更糟的是，仓库里还有一只据说很凶的乌鸦。你一边找出口，一边和它谈判。', effects: { intelligence: 3, agility: 2 }, exp: 14, minLevel: 2, weight: 1 },
  { id: 'science-lab', title: '黑科技实验', description: '科学部的学长拦住你，说他发明的「重力手环」需要一个志愿者。你看着手环上闪烁的警告灯，觉得这事不太妙。', effects: { intelligence: 3, luck: 1 }, exp: 15, minLevel: 2, weight: 1 },
  { id: 'midnight-training', title: '深夜特训', description: '夜深人静时，学长把你叫到空无一人的训练场，说要传你一招秘技，条件是「明天不许说出去」。', effects: { strength: 3, agility: 2 }, exp: 15, minLevel: 2, weight: 1 },
  { id: 'friendship-match', title: '校际替补', description: '校际友谊赛前，主力队员意外受伤，教练的目光扫过替补席，最终停在你身上：「你上。」', effects: { agility: 3, vitality: 2 }, exp: 16, minLevel: 2, weight: 1 },
  { id: 'library-mystery', title: '深夜翻书声', description: '闭馆后的图书馆传来翻书声，你蹑手蹑脚地循声而去，看见一本没人碰的书自己在翻页，停在了写着你名字的那一页。', effects: { intelligence: 3, luck: 2 }, exp: 15, minLevel: 2, weight: 1 },
  { id: 'city-treasure', title: '城市寻宝', description: '周末的城市寻宝活动，线索一路指向老城区。你蹲在废弃钟楼底下，挖出一只生锈的铁盒，里面躺着一张泛黄的旧地图。', effects: { agility: 2, intelligence: 2 }, exp: 14, minLevel: 2, weight: 1 },
  { id: 'kendo-duel', title: '剑道挑战', description: '剑道部的主将把竹刀横在你面前，声音平静：「听说你很能打，来一场。」围观的人群自动让出一片空地。', effects: { strength: 3, agility: 2 }, exp: 15, minLevel: 2, weight: 1 },
  { id: 'mystery-regular', title: '神秘常客', description: '打工的店里来了位神秘常客，每天打烊前点同一份套餐，临走时总会多留下一句没头没尾的话，像是在暗示什么。', effects: { charisma: 2, luck: 2 }, exp: 14, minLevel: 2, weight: 1 },
  { id: 'radio-poem', title: '深夜电台', description: '你鼓起勇气打进深夜电台，念了自己写的投稿。主持人沉默片刻，说你写的东西让他想起十年前没能说出口的话。', effects: { charisma: 3, luck: 1 }, exp: 13, minLevel: 2, weight: 1 },
  { id: 'info-broker', title: '情报贩子', description: '地下街的角落坐着一位自称「情报贩子」的墨镜大叔，他说只要帮他一个小忙，就告诉你一个「关于你的秘密」。', effects: { intelligence: 3, charisma: 1 }, exp: 14, minLevel: 2, weight: 1 },
  { id: 'isekai-call', title: '异世界召唤', description: '一阵强光过后，你出现在陌生的王座上，面前单膝跪着一位骑士：「魔王军来了，陛下，请下令。」你还没搞清自己是谁。', effects: { luck: 3, charisma: 2 }, exp: 17, minLevel: 3, weight: 1 },
  { id: 'hell-training', title: '地狱特训', description: '师傅宣布为你量身定制「地狱特训」：凌晨四点起床，背着沙袋跑山，午饭前做完三百个俯卧撑。第一天结束，你连筷子都拿不稳。', effects: { strength: 3, vitality: 2 }, exp: 16, minLevel: 3, weight: 1 },
  { id: 'mecha-alert', title: '敌袭警报', description: '机甲训练基地拉响红色警报，你被推进驾驶舱待命。舱门合拢的瞬间，你的心跳和机体的引擎声慢慢同步。', effects: { intelligence: 3, strength: 2 }, exp: 17, minLevel: 3, weight: 1 },
  { id: 'power-awaken', title: '失控觉醒', description: '情急之下你觉醒了某种力量，却完全控制不住——它震碎了教室的三块窗户，也把围观的你吓得不轻。', effects: { luck: 3, agility: 2 }, exp: 16, minLevel: 3, weight: 1 },
  { id: 'final-eve', title: '决赛前夜', description: '决赛前夜，对手的教练亲自送来一瓶水：「小同学，喝点水，明天好好打。」你盯着瓶口，总觉得哪里不对劲。', effects: { intelligence: 3, luck: 1 }, exp: 16, minLevel: 3, weight: 1 },
  { id: 'urban-legend', title: '七大不可思议', description: '你决定调查学校流传的「七大不可思议」，在深夜的旧校舍走廊里，你数到了第八个。', effects: { intelligence: 3, agility: 2 }, exp: 16, minLevel: 3, weight: 1 },
  { id: 'typhoon-night', title: '台风救援', description: '台风夜，老城区传来求救声。你顶着风雨冲进摇摇欲坠的屋檐下，把困住的孩子抱了出来，积水没过你的膝盖。', effects: { strength: 3, vitality: 2 }, exp: 17, minLevel: 3, weight: 1 },
  { id: 'stolen-day', title: '消失的一天', description: '你发现自己的记忆缺了一块——本周的某一天像是被人偷走了。你顺着日历上的涂鸦痕迹，开始追查那一天的自己去了哪里。', effects: { intelligence: 3, luck: 2 }, exp: 17, minLevel: 3, weight: 1 },
  { id: 'demon-king', title: '魔王城委托', description: '冒险者公会的墙上贴着一张奇怪的委托：往魔王城送一封信，报酬是一袋金币加一句「谢谢」。你接下委托时，柜台后的姑娘冲你竖起了大拇指。', effects: { agility: 3, luck: 2 }, exp: 17, minLevel: 3, weight: 1 },
  { id: 'shadow-self', title: '心之试炼', description: '幻境中，另一个你从镜子里走出来，他拥有你全部的记忆，却想取代你。「你确定，你真的比我强吗？」他笑着问。', effects: { intelligence: 3, charisma: 2 }, exp: 16, minLevel: 3, weight: 1 },
  { id: 'underground-ring', title: '地下格斗场', description: '朋友硬拉你去看地下格斗赛，谁知主持人把话筒怼到你面前：「这位观众看起来身手不错，要不要上来玩玩？」', effects: { strength: 3, vitality: 2 }, exp: 16, minLevel: 3, weight: 1 },
  { id: 'backyard-rip', title: '后院裂缝', description: '你家后院忽然裂开一道发光的缝隙，里面传来断断续续的求救声。你握紧手电筒，深吸一口气迈了进去。', effects: { luck: 3, intelligence: 2 }, exp: 17, minLevel: 3, weight: 1 },
  { id: 'ace-pilot', title: '王牌机师', description: '模拟驾驶舱的测试里，你打出了历史最高分。教官摘下墨镜打量你良久，最后只说了一句：「明天，来正式机组报到。」', effects: { intelligence: 3, agility: 2 }, exp: 16, minLevel: 3, weight: 1 },
  // ===== 史诗（8 个，minLevel 4/5/6）=====
  { id: 'festival-finale', title: '祭典压轴', description: '文化祭压轴演出，舞台的聚光灯轰然打在你身上，台下三千人的目光和欢呼汇成一片海。你握着话筒，手心全是汗。', effects: { charisma: 4, agility: 2 }, exp: 20, minLevel: 4, weight: 1 },
  { id: 'champion-night', title: '冠军前夜', description: '全国大赛决赛的前一夜，你梦见对手的每一个动作都被放慢成帧。醒来时，你发现自己在枕边写满了密密麻麻的战术笔记。', effects: { intelligence: 4, luck: 1 }, exp: 19, minLevel: 4, weight: 1 },
  { id: 'mecha-deploy', title: '机甲首战', description: '巨型机甲在城市中心完成首次实战部署，你坐在主驾驶舱里，第一次真正握住操纵杆。整座城市都在你的脚下。', effects: { strength: 4, vitality: 3 }, exp: 22, minLevel: 4, weight: 1 },
  { id: 'future-kid', title: '未来少年', description: '一个自称来自未来的少年拦住你：「三年后的今天，你会在那座桥上拯救世界。」他留下半张照片，照片里的人确实是你。', effects: { luck: 4, charisma: 2 }, exp: 20, minLevel: 4, weight: 1 },
  { id: 'bond-awaken', title: '羁绊觉醒', description: '伙伴们被逼到绝境，你体内沉睡的力量终于苏醒。他们喊着你的名字，你身后的光随着那一声声呼唤越来越亮。', effects: { strength: 4, charisma: 3 }, exp: 22, minLevel: 5, weight: 1 },
  { id: 'demon-lord', title: '魔王现身', description: '魔王亲自降临，天空被染成暗红色，整座城市的警报连成一片。你推开颤抖的人群，一步一步走向最前线。', effects: { strength: 4, vitality: 3 }, exp: 24, minLevel: 5, weight: 1 },
  { id: 'time-redemption', title: '回到过去', description: '你回到了那个改变一切的节点——十年前的那个下午，你终于看清了当初没来得及看清的真相。', effects: { intelligence: 4, luck: 3 }, exp: 22, minLevel: 5, weight: 1 },
  { id: 'final-battle', title: '最终决战', description: '最终决战在燃烧的天空下打响，你与宿敌隔着崩裂的大地对峙。风卷起灰烬，你们的影子在火光中拉得很长。', effects: { strength: 5, agility: 3 }, exp: 26, minLevel: 6, weight: 1 },
]
