/**
 * 小说主题：新增事件。
 */
import type { AdventureEvent } from '../themes.js'

export const NOVEL_NEW_EVENTS: readonly AdventureEvent[] = [
  { id: 'borrower-return', title: '借书人', description: '图书馆闭馆前一分钟，有人把刚还的书又借了回去，说书里夹着他半辈子的人生。你瞥见书名，正是你此刻正在经历的那一本。', effects: { luck: 3, intelligence: 1 }, exp: 10, weight: 1 },
  { id: 'margin-notes', title: '批注读者', description: '二手书里，前一位读者用铅笔写满了批注，在页边跟你吵了一整本书的架，末了留下一句：「看到这里，你应该懂我了。」', effects: { intelligence: 4, charisma: 1 }, exp: 12, weight: 1 },
  { id: 'dropped-serial', title: '断更之夜', description: '你追了三年的连载在关键处断更，盯着「未完待续」四个字，你忽然来了灵感，把结局自己脑补了出来。', effects: { intelligence: 3, luck: 2 }, exp: 11, weight: 1 },
  { id: 'next-chapter-preview', title: '章末预告', description: '每章末尾都印着一句下章预告，而今天的预告写着的事，恰好是你明天就要去做的。', effects: { luck: 4 }, exp: 10, weight: 1 },
  { id: 'typo-correction', title: '改正错字', description: '你在一本旧书里发现一个错别字，提笔轻轻改正，书页竟微微发烫，像在向你道谢。', effects: { intelligence: 2, luck: 2 }, exp: 9, weight: 1 },
  { id: 'bookmark-letter', title: '书签来信', description: '旧书里掉出一枚手工书签，背面写着一行字：「读到这里的你，替我多看几眼结局。」', effects: { charisma: 3, vitality: 1 }, exp: 10, weight: 1 },
  { id: 'shifting-toc', title: '目录异动', description: '目录页在灯下看久了，章节标题竟悄悄变化，最新多出的一章，名叫《无名读者的清晨》。', effects: { intelligence: 3, luck: 1 }, exp: 11, weight: 1 },
  { id: 'rainy-bookstall', title: '雨天书摊', description: '雨天，路边书摊的老板用塑料布护着书，自己却淋得透湿。你多买了两本最旧的。', effects: { charisma: 2, luck: 2 }, exp: 10, weight: 1 },
  { id: 'trial-reading', title: '试读章节', description: '书店的新书区，你随手翻开一本试读，第一段描写的正是你今早的经历，一字不差，连领带的颜色都对。', effects: { luck: 5 }, exp: 12, weight: 1 },
  { id: 'blank-last-page', title: '空白末页', description: '全书最后一页是空白的，你在上面写下一行字，合上书时，听见一声极轻的叹息。', effects: { charisma: 4, intelligence: 1 }, exp: 11, weight: 1 },
  { id: 'broken-volume', title: '古籍修复', description: '你在旧书摊淘到一册散页的古籍，花了整个下午，把纸页按页码一片片重新排好，像拼起一具旧梦。', effects: { intelligence: 3, agility: 1 }, exp: 10, weight: 1 },
  { id: 'dialect-reading', title: '方言朗读', description: '社区读书会最后一排，有人用方言朗读一首诗，全场安静得只剩雨声。你记住了那种陌生又温柔的腔调。', effects: { charisma: 3, vitality: 1 }, exp: 9, weight: 1 },
  { id: 'pressed-rose', title: '书页藏花', description: '诗集翻到一半，一朵压成干花的玫瑰从书页间滑落，香气淡得几乎不存在，却让整页诗都活了过来。', effects: { luck: 3, charisma: 1 }, exp: 10, weight: 1 },
  { id: 'preface-writer', title: '序言旧识', description: '你偶然发现，某本传记的序言作者竟是你多年的旧识，他在序里把你写成了全篇的「主角」。', effects: { charisma: 4 }, exp: 11, weight: 1 },
  { id: 'twin-copies', title: '平行定价', description: '图书馆书架上，两本一模一样的小说并排立着，只有封底的定价差了九分钱，像两个平行世界的分身。', effects: { intelligence: 2, luck: 2 }, exp: 9, weight: 1 },
  { id: 'stallholder-prophet', title: '摊主预言', description: '旧书摊老板把一本书塞进你怀里，说「三天后你会需要它」。三天后，你果然在书里找到了答案。', effects: { luck: 4, intelligence: 1 }, exp: 12, weight: 1 },
  { id: 'penciled-circles', title: '圈点句子', description: '你借来的书里，重点句被前一位读者用铅笔圈过，圈出的恰好是此刻正困扰你的那一句。', effects: { intelligence: 4, luck: 1 }, exp: 11, weight: 1 },
  { id: 'flyleaf-inscription', title: '扉页题词', description: '扉页上有人用钢笔题了一行字：「赠给读到这里的陌生人。」没有署名，也没有日期。', effects: { charisma: 2, luck: 2 }, exp: 9, weight: 1 },
  { id: 'all-nighter', title: '通宵追读', description: '你通宵追完一整部连载，合上书时天已大亮，眼睛发酸，脑子里却全是没写完的下一章。', effects: { intelligence: 3, vitality: -2 }, exp: 12, weight: 1 },
  { id: 'dual-endings', title: '双结局', description: '你先后读到同一本书的两种结局，两个结尾都让你意难平，最后你在心里替作者写下了第三种。', effects: { intelligence: 3, charisma: 2 }, exp: 12, weight: 1 },
  { id: 'grammar-clinic', title: '病句门诊', description: '你给杂志「读者来信」栏提了一个病句疑问，编辑回信说会认真考虑，还夸你观察细致。', effects: { intelligence: 2, charisma: 1 }, exp: 9, weight: 1 },
  { id: 'skipped-chapters', title: '跳页阅读', description: '你翻书时不小心从第三章直接跳到第七章，竟毫无违和，仿佛书页之间自己补全了情节。', effects: { luck: 3, intelligence: 2 }, exp: 11, weight: 1 },
  { id: 'character-awakening', title: '人物觉醒', description: '你合上书时，书里的配角忽然开口：「下次翻开，记得让我多活几章。」', effects: { charisma: 3, luck: 1 }, exp: 10, weight: 1 },
  { id: 'reading-notes', title: '读后随笔', description: '你写完一篇读后随笔夹进书里，几天后再翻，页间多了一行陌生笔迹：「你的理解，比作者更深。」', effects: { intelligence: 3, charisma: 2 }, exp: 11, weight: 1 },
  { id: 'bargain-hunting', title: '二手书虫', description: '你在旧书堆里翻找了一下午，灰尘呛得直打喷嚏，但总算淘到了绝版的第一册。', effects: { luck: 3, vitality: -1 }, exp: 10, weight: 1 },
  { id: 'audiobook-voice', title: '有声书声', description: '你戴着耳机听有声书，主播念到你名字的那一刻，你恰好走到那本书里写过的旧街道。', effects: { luck: 4, agility: 1 }, exp: 12, weight: 1 },
  { id: 'pencil-sketch', title: '铅笔小像', description: '书页空白处有人用铅笔画了一幅小像，眉眼与你神似。你抬头，对面桌的人正在翻同一本书。', effects: { luck: 3, charisma: 2 }, exp: 11, weight: 1 },
  { id: 'rare-books-room', title: '典藏书库', description: '你替朋友还书时误入典藏书库，满墙古籍在灯光下安静得像一群睡着的老者，空气里全是墨香。', effects: { intelligence: 3, vitality: 1 }, exp: 10, weight: 1 },
  { id: 'flash-fiction', title: '便签故事', description: '你在便签上随手写了个三百字的小故事，被同事捡去贴在茶水间，竟有好几个人来问作者是谁。', effects: { charisma: 4, intelligence: 1 }, exp: 12, weight: 1 },
  { id: 'book-name-omen', title: '书名成谶', description: '你买的那本《迷路指南》里夹着一张手绘地图，终点恰好是你明天要出差的城市。', effects: { luck: 4, intelligence: 1 }, exp: 11, weight: 1 },
  { id: 'translation-error', title: '翻译之误', description: '你在外文书里发现一处翻译错误，改正之后整段文字忽然有了韵味，像原作者隔着时空向你致意。', effects: { intelligence: 4, luck: 1 }, exp: 11, weight: 1 },
  { id: 'shelf-encounter', title: '书架偶遇', description: '你伸手去够书架顶层时，另一只手同时搭上了那本书。两个人相视一笑，都松了手。', effects: { charisma: 3, luck: 2 }, exp: 10, weight: 1 },
  { id: 'prologue-reread', title: '序章重读', description: '你心血来潮重读一本书的序章，才发现第一段就埋下了结局的伏笔，当年竟全然没有注意。', effects: { intelligence: 4 }, exp: 10, weight: 1 },
  { id: 'book-crossing', title: '漂流书笺', description: '小区的漂流书架上，你留下的书被人读过后，夹回一张手写纸条：「谢谢你，陌生人。」', effects: { charisma: 3, luck: 1 }, exp: 9, weight: 1 },
  { id: 'all-night-proofreading', title: '熬夜校对', description: '你帮出版社赶稿校对到凌晨，抓出二十多处错漏，人也快散了架，却第一次觉得文字是有重量的。', effects: { intelligence: 4, vitality: -2 }, exp: 13, weight: 1 },
  { id: 'recipe-notes', title: '菜谱笔记', description: '你在旧菜谱的夹缝里发现一页手写笔记，记着一种失传点心的做法，末了写着「此页勿示于人」。', effects: { luck: 3, intelligence: 2 }, exp: 11, weight: 1 },
  { id: 'pillow-note', title: '枕边留字', description: '你枕边那本书每晚都被翻到同一页，某天清晨醒来，那一页多了一行铅笔小字：「晚安。」', effects: { luck: 3, charisma: 1 }, exp: 10, weight: 1 },
  { id: 'overdue-book', title: '借书逾期', description: '你为读完那本好书错过还书期限，被图书馆罚了款，可合上书时，你只觉得这一趟值了。', effects: { intelligence: 3, luck: -1 }, exp: 10, weight: 1 },
  { id: 'gap-on-shelf', title: '书脊缺口', description: '书架上一排旧书，唯独中间那本被人抽走，留下一个缺口。你忍不住把自己的一本书补了进去。', effects: { charisma: 2, luck: 2 }, exp: 9, weight: 1 },
  { id: 'wordless-notebook', title: '无字天书', description: '你买到一本号称「无字天书」的空白笔记本，扉页印着一行小字：「只写给勇敢的人看。」', effects: { intelligence: 3, luck: 2 }, exp: 11, weight: 1 },
  { id: 'pirate-typo', title: '盗版笑料', description: '你在盗版书上遇到一个错得离谱的字，当场笑出声，旁边的乘客都奇怪地看着你。', effects: { luck: 2, charisma: 1 }, exp: 9, weight: 1 },
  { id: 'afterword-blank', title: '后记补全', description: '作者在书末后记里说「还有很多话没说完」，你在空白处替他把话写完，寄去了出版社。', effects: { charisma: 3, intelligence: 2 }, exp: 11, weight: 1 },
  { id: 'chapter-title', title: '黎明章题', description: '风把书页吹到某一页，章节标题是《黎明前的决定》，而窗外恰好天将亮未亮。', effects: { luck: 3, agility: 1 }, exp: 10, weight: 1 },
  { id: 'yellowed-novel', title: '泛黄旧书', description: '你从阁楼翻出一本泛黄的小说，出版年份比你出生还早，书里夹着一张那个年代的公交票。', effects: { luck: 3, intelligence: 1 }, exp: 10, weight: 1 },
  { id: 'recitation-contest', title: '朗读比赛', description: '你被拉去参加朗读比赛，临场抽到一篇写「勇气」的文章，读完后台下安静了三秒，掌声才轰然响起。', effects: { charisma: 5, vitality: -1 }, exp: 13, weight: 1 },
  { id: 'childhood-serial', title: '童年连载', description: '你整理抽屉时翻出初中时和同桌合写的连载小说，字迹稚嫩，剧情却意外地跌宕起伏。', effects: { intelligence: 2, charisma: 2 }, exp: 9, weight: 1 },
  { id: 'closing-shop', title: '打烊留灯', description: '你在书店待到打烊，店员没有赶你，只把一盏灯留给你：「把这一章读完再走。」', effects: { charisma: 3, luck: 1 }, exp: 10, weight: 1 },
  { id: 'handwritten-poems', title: '手抄诗集', description: '邻居奶奶递给你一册她年轻时手抄的诗集，说其中一首是为你写的，虽然那时你还没出生。', effects: { charisma: 4, vitality: 1 }, exp: 11, weight: 1 },
  { id: 'preface-postscript', title: '序跋对答', description: '一本书的序和跋像两个人在隔空吵架，你读着读着，竟觉得他们也在和你说话。', effects: { intelligence: 3, charisma: 1 }, exp: 10, weight: 1 },
  { id: 'illustration-secret', title: '插图暗影', description: '你发现书中的插画比正文多了一个细节：角落的树后，画着一个正在读书的人，像极了现在的你。', effects: { intelligence: 3, luck: 2 }, exp: 11, weight: 1 },
  { id: 'proofreader', title: '校书人', description: '你把一本错漏百出的旧书认真校对了一遍，翻动书页的声音，也变得整齐而悦耳。', effects: { intelligence: 3, agility: 1 }, exp: 10, weight: 1 },
  { id: 'title-debate', title: '标题之争', description: '朋友为小说取什么标题争得面红耳赤，你随口提了一个，全场安静，随即一致通过。', effects: { charisma: 4, intelligence: 1 }, exp: 11, weight: 1 },
  { id: 'reader-letter', title: '读者来信', description: '你收到一封寄错的信，收件人是一本书里的角色。你犹豫片刻，还是替他回了信。', effects: { charisma: 3, luck: 2 }, exp: 10, weight: 1 },
  { id: 'old-love-reread', title: '重读旧爱', description: '你重读年轻时最爱的小说，发现文笔远没有记忆中好，怅然若失，却也读懂了当年的自己。', effects: { intelligence: 2, charisma: -1 }, exp: 9, weight: 1 },
  { id: 'serial-ending', title: '完结撒花', description: '连载更完最后一章那天，你在评论区写下「谢谢」，收到作者本人一句「也谢谢你」。', effects: { charisma: 3, luck: 2 }, exp: 12, weight: 1 },
  { id: 'forbidden-section', title: '禁书区', description: '你误入图书馆深处的禁书区，管理员只当没看见，低声说：「借阅时间，一炷香。」', effects: { intelligence: 5, luck: 2 }, exp: 15, minLevel: 2, weight: 1 },
  { id: 'author-interview', title: '作者专访', description: '你偶遇一位神秘作家，他请你喝咖啡，却只谈你的事，闭口不提自己的新书。', effects: { charisma: 5, intelligence: 2 }, exp: 14, minLevel: 2, weight: 1 },
  { id: 'manuscript-page', title: '残稿一页', description: '旧书夹层里掉出一页手写残稿，字迹与你昨夜梦里的句子一模一样，连墨渍的位置都相同。', effects: { luck: 4, intelligence: 3 }, exp: 15, minLevel: 2, weight: 1 },
  { id: 'character-cast', title: '选角试镜', description: '有人拿着剧本拦住你，说你活脱脱是书里某个角色，想请你去试镜，片酬还相当可观。', effects: { charisma: 4, agility: 2 }, exp: 14, minLevel: 2, weight: 1 },
  { id: 'chapter-gap', title: '断章之隙', description: '你发现书里缺了一章，凭前后文推演出缺失的情节，作者后来竟按你的补写发布了单行本。', effects: { intelligence: 6, luck: 1 }, exp: 16, minLevel: 2, weight: 1 },
  { id: 'book-mob', title: '书痴集会', description: '你误入一场地下读书会，众人正为「结局该不该圆满」吵得不可开交，有人连凳子都举起来了。', effects: { charisma: 4, intelligence: 2 }, exp: 14, minLevel: 2, weight: 1 },
  { id: 'plot-leak', title: '剧透之险', description: '有人在书外向你剧透你的命运，你捂着耳朵逃开，却还是记住了半个关键情节，心里痒痒的。', effects: { intelligence: 3, agility: 3 }, exp: 14, minLevel: 2, weight: 1 },
  { id: 'ink-smell', title: '油墨未干', description: '你买到一本油墨未干的新书，文字在纸面上微微蠕动，像刚出生的小动物，还带着温度。', effects: { intelligence: 4, luck: 2 }, exp: 15, minLevel: 2, weight: 1 },
  { id: 'library-cat', title: '图书馆之猫', description: '图书馆常驻的那只猫叼来一枚旧钥匙，钥匙柄上刻着一个章节号，恰好是全书最关键的一章。', effects: { luck: 5, agility: 1 }, exp: 14, minLevel: 2, weight: 1 },
  { id: 'ghost-writer', title: '代笔邀请', description: '一位富商请你代笔写他的传记，条件是不能写任何他不喜欢的事。你看着那叠支票，犹豫了很久。', effects: { charisma: 4, intelligence: 2 }, exp: 15, minLevel: 2, weight: 1 },
  { id: 'serial-killer-novel', title: '恐怖连载', description: '你常看的恐怖连载更新了，最新一章描述的案发现场，正是你昨天路过的那条小巷。', effects: { intelligence: 4, luck: 2 }, exp: 16, minLevel: 2, weight: 1 },
  { id: 'poetry-duel', title: '斗诗', description: '街角的诗会上，有人指着你出题，全场等着你即兴对句。你的上联一落，连摊主都忘了收钱。', effects: { charisma: 4, intelligence: 3 }, exp: 15, minLevel: 2, weight: 1 },
  { id: 'book-cover', title: '封面之约', description: '出版社请你去拍一本小说的封面，摄影师说：「你往那儿一站，故事感就来了。」', effects: { charisma: 5, agility: 1 }, exp: 14, minLevel: 2, weight: 1 },
  { id: 'hidden-chapter', title: '隐藏章节', description: '你发现书里有一章被刻意撕去，而撕痕的形状，恰好与你贴身收藏的那枚书签完全吻合。', effects: { intelligence: 5, luck: 3 }, exp: 17, minLevel: 3, weight: 1 },
  { id: 'author-deadline', title: '作者赶稿', description: '你拜访一位拖稿三年的作家，他顶着乱发问你：「如果主角不想继续写下去，该怎么办？」', effects: { charisma: 4, intelligence: 3 }, exp: 16, minLevel: 3, weight: 1 },
  { id: 'reader-backlash', title: '读者反噬', description: '你替作者回复读者留言，一条措辞严厉的差评让你一夜没睡好，却也让你想明白了写作的意义。', effects: { charisma: 3, intelligence: 4 }, exp: 16, minLevel: 3, weight: 1 },
  { id: 'sequel-hook', title: '续作伏笔', description: '你读到一部完结小说的最后一行，那里藏着下一部的伏笔——而伏笔里的主角，写着你的名字。', effects: { luck: 5, intelligence: 3 }, exp: 17, minLevel: 3, weight: 1 },
  { id: 'literary-festival', title: '文学节', description: '文学节签售会上，一位老作家在你的书上签名，抬头看了你很久，说：「你是书里的人。」', effects: { charisma: 5, luck: 2 }, exp: 16, minLevel: 3, weight: 1 },
  { id: 'dialogue-practice', title: '对白练习', description: '你受邀扮演一部话剧里的角色，排练时即兴改了一句台词，导演当场拍板采用。', effects: { charisma: 4, agility: 3 }, exp: 16, minLevel: 3, weight: 1 },
  { id: 'footnotes-fight', title: '注释之争', description: '你发现一部古籍的两个版本注释互相矛盾，连夜查证，竟为其中一方找到了铁证。', effects: { intelligence: 6, charisma: 1 }, exp: 17, minLevel: 3, weight: 1 },
  { id: 'bookworm-bet', title: '藏书赌约', description: '一位藏书家与你打赌：他出题，你在他的书房里找出符合题意的书，找不到就得输给他一顿饭。', effects: { intelligence: 5, luck: 2 }, exp: 16, minLevel: 3, weight: 1 },
  { id: 'banned-book', title: '查禁之书', description: '你在旧书摊买下一本被查禁的书，摊主压低声音说：「看完记得还回来，别让人知道。」', effects: { intelligence: 4, luck: 3 }, exp: 16, minLevel: 3, weight: 1 },
  { id: 'serial-fan', title: '铁杆读者', description: '一位自称看过你「所有章节」的读者找到你，逐条背出你的经历，连你自己都忘了的细节，他都记得。', effects: { charisma: 4, luck: 3 }, exp: 16, minLevel: 3, weight: 1 },
  { id: 'rewrite-offer', title: '重写邀约', description: '出版社希望你把一部过气的经典重写成当代版本，原作者的后人只提了一个要求：别把魂写没了。', effects: { intelligence: 5, charisma: 2 }, exp: 17, minLevel: 3, weight: 1 },
  { id: 'midnight-store', title: '午夜书坊', description: '一间只在午夜营业的书坊，老板不问你要什么书，只问：「今天想成为什么样的人？」', effects: { luck: 4, charisma: 3 }, exp: 16, minLevel: 3, weight: 1 },
  { id: 'protagonist-trial', title: '主角审判', description: '你被一群读者「审判」，他们举着「人设崩塌」「剧情注水」的牌子，要求你当众自证清白。', effects: { charisma: 4, intelligence: 3 }, exp: 17, minLevel: 3, weight: 1 },
  { id: 'author-reveal', title: '作者现身', description: '你受邀参加一场「作者与主角」的线下见面会，全场读者都在等你亲口说一句：「谢谢你们读到今天。」', effects: { charisma: 6, luck: 2 }, exp: 21, minLevel: 4, weight: 1 },
  { id: 'novel-reality', title: '小说入侵', description: '你合上眼，书中的城市开始在现实里浮现轮廓，街角的报亭摆上了印着「关于你」的报纸。', effects: { intelligence: 5, luck: 3 }, exp: 20, minLevel: 4, weight: 1 },
  { id: 'deleted-scenes', title: '删除章节', description: '你偶然得到作者删掉的章节，里面记载着主角不为人知的过去——以及一个反复出现的名字：你。', effects: { intelligence: 6, charisma: 2 }, exp: 22, minLevel: 4, weight: 1 },
  { id: 'reader-army', title: '读者军团', description: '全网读者自发为你应援，评论区刷满了同一句话：「别让主角受委屈。」你第一次知道，被期待是这么重的事。', effects: { charisma: 6, luck: 3 }, exp: 23, minLevel: 5, weight: 1 },
  { id: 'genre-collision', title: '题材碰撞', description: '你所在的故事与另一本书发生「题材碰撞」，两个世界的规则开始互相覆盖，你得在规则乱流里站稳。', effects: { agility: 5, intelligence: 4 }, exp: 22, minLevel: 5, weight: 1 },
  { id: 'plot-twist', title: '惊天反转', description: '作者在最后一刻改写了你的设定：你一直以为自己是配角，其实你才是全书真正的暗线主角。', effects: { intelligence: 6, luck: 3 }, exp: 23, minLevel: 5, weight: 1 },
  { id: 'universe-rewrite', title: '全书改写', description: '读者投票决定重写整本书，而你必须在七十二小时内证明，「现在的你」值得被保留在纸页之间。', effects: { charisma: 6, intelligence: 4 }, exp: 25, minLevel: 6, weight: 1 },
  { id: 'final-draft', title: '最终稿', description: '作者把定稿的最后一章交到你手上：「结局由你决定。」所有读者都在屏幕另一端屏息等待。', effects: { luck: 5, charisma: 4 }, exp: 26, minLevel: 6, weight: 1 },
]
