/**
 * 科幻主题：新增事件。
 */
import type { AdventureEvent } from '../themes.js'

export const SCI_FI_NEW_EVENTS: readonly AdventureEvent[] = [
  { id: 'space-post-office', title: '太空邮局', description: '空间站邮局的机械臂把一封地址模糊的信塞进你怀里，信封上写着「寄给银河里最善良的陌生人」，收信人一栏却是你的名字。', effects: { charisma: 2, luck: 1 }, exp: 10, weight: 1 },
  { id: 'zero-g-gym', title: '失重健身房', description: '离心舱健身房的跑步机又坏了，你用一根弹力绳在零重力下做拉伸，退役航天员教练路过，夸你姿势比新兵还标准。', effects: { agility: 2, vitality: 1 }, exp: 10, weight: 1 },
  { id: 'galley-chef-ai', title: '舰船大厨', description: '舰载厨房的自动厨师坚持要为你「露一手」，它调制的合成牛排带着一股淡淡的机油味，但口感意外地不错。', effects: { vitality: 2, luck: 1 }, exp: 9, weight: 1 },
  { id: 'gas-giant-aurora', title: '行星极光', description: '舷窗外，气态巨行星的磁极正下着一场绵延数千公里的极光雨，你把画面录下来，打算发给地球的老朋友。', effects: { charisma: 1, luck: 2 }, exp: 9, weight: 1 },
  { id: 'sleepless-meditation', title: '彻夜冥想', description: '睡眠舱的白噪音 AI 教你一段深度呼吸法，你练得忘了时间，错过早餐窗口。不过整夜无梦，头脑前所未有地清醒。', effects: { intelligence: 2, vitality: -1 }, exp: 10, weight: 1 },
  { id: 'hydroponic-deck', title: '水培甲板', description: '水培甲板的园艺师教你给番茄藤修剪枝条，临别塞给你一枚刚摘的太空番茄，说它比地球上的甜三个数量级。', effects: { vitality: 2, charisma: 1 }, exp: 10, weight: 1 },
  { id: 'zero-g-shower', title: '零重力淋浴', description: '零重力淋浴舱的吸力阀又卡住了，你在飘满水珠的舱室里手忙脚乱，被隔壁舱的大妈用一句祖传口诀解救。', effects: { agility: 1, luck: 2 }, exp: 9, weight: 1 },
  { id: 'station-radio-dj', title: '深夜电台', description: '空间站的深夜电台读了你寄去的点歌留言，主持人把你的昵称念得字正腔圆，还说今晚的听众来信你当压轴。', effects: { charisma: 2, luck: 1 }, exp: 10, weight: 1 },
  { id: 'wobbly-repair-bot', title: '修理机器人', description: '一台维修机器人卡在走廊转角，一边打转一边发出求救音。你帮它重新校准了陀螺仪，它用机械臂给你比了个心。', effects: { intelligence: 1, charisma: 2 }, exp: 9, weight: 1 },
  { id: 'drone-pizza', title: '无人机外卖', description: '星际外卖无人机把餐盒送到你手里时，附赠一张手写便签：「今日推荐：火星辣酱，请谨慎服用。」署名是一只猫爪印。', effects: { luck: 2, vitality: 1 }, exp: 10, weight: 1 },
  { id: 'memory-backup-kiosk', title: '记忆备份站', description: '记忆备份站推出「免费体验一次」活动，你在机器里躺了十分钟，出来时想起了一段早已遗忘的童年旋律。', effects: { intelligence: 2, luck: 1 }, exp: 10, weight: 1 },
  { id: 'botanical-dome', title: '植物穹顶', description: '植物穹顶里那棵百年老树开花了，管理员说它二十年才开一次。你赶上了，还顺手捡到一枚幸运种子。', effects: { luck: 3, vitality: 1 }, exp: 11, weight: 1 },
  { id: 'coffee-art', title: '零重力拉花', description: '咖啡师在零重力下给你拉了一杯螺旋星云图案的拿铁，奶泡在失重环境里缓缓旋转，你举着杯子舍不得喝。', effects: { charisma: 1, luck: 1 }, exp: 9, weight: 1 },
  { id: 'flea-market-starmap', title: '旧货星图', description: '旧货市场的摊主说他这张星图是祖传的，上面标注的航路比官方星图多出三条，你半价买下了它。', effects: { intelligence: 2, luck: 1 }, exp: 11, weight: 1 },
  { id: 'antique-nav-unit', title: '古董导航仪', description: '回收站里一台古董导航仪还能开机，像素风航线图闪着绿光，有人出价要收，你却决定自己留着。', effects: { intelligence: 2, agility: 1 }, exp: 10, weight: 1 },
  { id: 'starmap-graffiti', title: '星图涂鸦', description: '走廊的星图投影上被人画了一条歪歪扭扭的「近路」，你顺着箭头走到头，发现了一台藏起来的冰淇淋机。', effects: { luck: 2, agility: 1 }, exp: 11, weight: 1 },
  { id: 'space-pet-octopus', title: '失重章鱼', description: '货运舱里混进一只小章鱼，它把触手缠在你手腕上不肯松开。水手长说它认定了你当主人，你得给它起个名字。', effects: { charisma: 2, luck: 1 }, exp: 10, weight: 1 },
  { id: 'electric-spark-fruit', title: '电火花果', description: '外星摊主请你尝「家乡特产」，一种会发光、嚼起来像电火花的果子。你连吃三个，胃里像装了台小型反应堆。', effects: { vitality: 3, agility: -2 }, exp: 10, weight: 1 },
  { id: 'paper-library', title: '纸质图书馆', description: '空间站的图书馆有一整排纸质书，管理员说是「上个千年的遗产」。你借走一本，扉页上有人留了句手写祝福。', effects: { intelligence: 2, charisma: 1 }, exp: 10, weight: 1 },
  { id: 'arcade-cramp', title: '街机新纪录', description: '游戏厅角落那台上世纪街机被你打出了新纪录，围观者掌声雷动，只有你知道右手已经酸得举不起咖啡杯。', effects: { agility: 2, vitality: -1 }, exp: 10, weight: 1 },
  { id: 'training-simulator', title: '训练模拟舱', description: '你在训练模拟舱驾驶虚拟运输船穿越小行星带，全程零碰撞，教官在观察窗外朝你竖起了大拇指。', effects: { agility: 2, intelligence: 1 }, exp: 11, weight: 1 },
  { id: 'debris-sweep', title: '轨道清道夫', description: '你报名参加太空垃圾清理作业，用机械臂把一块报废卫星残骸推进大气层。任务结束，站长请你喝了杯热饮。', effects: { strength: 1, luck: 2 }, exp: 11, weight: 1 },
  { id: 'solar-panel-wipe', title: '帆板擦洗', description: '你系着安全绳擦洗太阳能帆板，零重力下滑行，阳光透过帆板投下一片金色光斑，你顺手清理了几处微陨石坑。', effects: { agility: 1, vitality: 1 }, exp: 9, weight: 1 },
  { id: 'relay-watch', title: '中继站值守', description: '你替值班员在中继站守了一夜，收听到一段来自深空探测器的加密讯号——那是它离家十年的第一声问候。', effects: { intelligence: 2, luck: 1 }, exp: 11, weight: 1 },
  { id: 'song-dedication', title: '电台点歌', description: '你在星际电台给地球的家人点了一首歌，主持人在节目里念了你的留言，说你「是全银河最会说话的人」。', effects: { charisma: 2, luck: 1 }, exp: 10, weight: 1 },
  { id: 'o2-false-alarm', title: '氧气误报', description: '氧气传感器突然尖叫，全站进入警报状态。最后查明是一只外星飞虫挡住了探头，你冷静的处置让站长记住了你。', effects: { intelligence: 2, charisma: 1 }, exp: 11, weight: 1 },
  { id: 'space-elevator', title: '太空电梯', description: '你搭乘太空电梯从轨道站下行到地表，蓝色星球在脚下缓缓展开。导游宣布你是今天的幸运乘客，免了票。', effects: { luck: 2, vitality: 1 }, exp: 10, weight: 1 },
  { id: 'moon-cafe', title: '月面咖啡馆', description: '月面基地的咖啡馆有扇正对地球的大窗，老板给你调了杯「故乡特调」，说是她祖母传下来的配方。', effects: { charisma: 1, vitality: 2 }, exp: 10, weight: 1 },
  { id: 'cryo-pod-inspection', title: '冷冻舱巡检', description: '你帮技师巡检冷冻睡眠舱，发现 7 号舱休眠参数偏了零点几度。技师说幸好发现得早，不然那哥们要做噩梦。', effects: { intelligence: 2, agility: 1 }, exp: 11, weight: 1 },
  { id: 'spacewalk', title: '舱外漫步', description: '你获准进行第一次舱外漫步，脚下是缓缓转动的星舰，身后是整片银河。你在面罩里轻轻哼起了歌。', effects: { agility: 2, luck: 1 }, exp: 12, weight: 1 },
  { id: 'stardust-collector', title: '星尘采集', description: '舰尾的星尘采集器里躺着一粒亮得不像话的尘粒，老研究员说它可能来自超新星遗迹，让你收进幸运瓶。', effects: { luck: 2, intelligence: 1 }, exp: 11, weight: 1 },
  { id: 'asteroid-mine', title: '小行星矿场', description: '小行星矿场的领班看你力气不错，让你顶了半天班，收工时分你一块拳头大的镍铁陨石当纪念品。', effects: { strength: 2, vitality: 1 }, exp: 11, weight: 1 },
  { id: 'antimatter-refuel', title: '反物质补给', description: '补给舰为你的船加注反物质燃料，你负责盯仪表盘。全程零故障，舰长说这是本季度头一次。', effects: { intelligence: 2, luck: 1 }, exp: 11, weight: 1 },
  { id: 'interstellar-visa', title: '星际签证处', description: '星际签证处排着长队，你帮一位不会填表的老奶奶搞定电子签证，她非要请你吃自制的星云糖。', effects: { charisma: 2, agility: 1 }, exp: 10, weight: 1 },
  { id: 'rest-stop-fuel', title: '幸运燃料', description: '银河服务区的机器人给你讲了个冷笑话，你笑到岔气，回过神才发现它已给你的车加满「幸运燃料」——账单贵得离谱。', effects: { luck: 2, intelligence: -1 }, exp: 10, weight: 1 },
  { id: 'mars-greenhouse', title: '火星温室', description: '火星温室里的土豆丰收了，农艺师教你用火星土壤种菜，还送你一袋「火星一号」品种的种子。', effects: { vitality: 2, intelligence: 1 }, exp: 10, weight: 1 },
  { id: 'jupiter-storm-view', title: '风暴观测', description: '你在木星观测站的观景台看了整整一小时大红斑，值班天文学家说你运气好，赶上它最活跃的这几天。', effects: { intelligence: 2, luck: 1 }, exp: 11, weight: 1 },
  { id: 'saturn-ring-tour', title: '土星环观光', description: '观光艇载着你穿过土星环，冰晶在舷窗外擦出细碎的光。领航员说，这片环比人类文明还要古老。', effects: { luck: 2, agility: 1 }, exp: 11, weight: 1 },
  { id: 'comet-observatory', title: '彗星观测站', description: '彗星观测站守夜时，你亲眼看见长彗星拖着淡蓝的尾巴划过深空。站长说它下一次回归要等两百年。', effects: { intelligence: 1, luck: 2 }, exp: 10, weight: 1 },
  { id: 'gravity-slide', title: '引力滑梯', description: '空间站新装的「引力滑梯」让你体验了一把失重俯冲，管理员说你的成绩是本站开张以来最快纪录。', effects: { agility: 2, vitality: 1 }, exp: 10, weight: 1 },
  { id: 'time-capsule', title: '时间胶囊', description: '翻修舱壁时你撬出一枚上世纪的时间胶囊，里面有一封信和一张全家福，按信封上的地址你把它寄了出去。', effects: { charisma: 1, luck: 1 }, exp: 10, weight: 1 },
  { id: 'translator-glitch', title: '翻译器故障', description: '随身翻译器把外星商人的话翻得驴唇不对马嘴，你干脆连比带划，最后居然谈成了一笔不错的生意。', effects: { charisma: 2, agility: 1 }, exp: 11, weight: 1 },
  { id: 'interstellar-chess', title: '星际象棋', description: '休息室里一台古老的象棋 AI 邀请你对弈，鏖战四十分钟后你以一步险棋取胜，屏幕上缓缓打出「学习完毕」。', effects: { intelligence: 3, luck: 1 }, exp: 12, weight: 1 },
  { id: 'hologram-pet', title: '全息宠物', description: '宠物店的全息小狐狸会跟着你跑，会钻进口袋蹭你，店员说它内置的情绪模块认定了你是主人。', effects: { charisma: 1, luck: 1 }, exp: 9, weight: 1 },
  { id: 'space-barber', title: '轨道理发师', description: '轨道理发师用一把激光梳子给你剪了新发型，剪完端详半天，说你「站上舰桥就是舰长的料」。', effects: { charisma: 2, luck: 1 }, exp: 9, weight: 1 },
  { id: 'dust-bot-race', title: '吸尘器竞速', description: '走廊里一台失控的吸尘机器人横冲直撞，你追了半条走廊，用一个垃圾桶盖把它扣住，围观群众给它起名「闪电」。', effects: { agility: 2, charisma: 1 }, exp: 10, weight: 1 },
  { id: 'mystery-parcel', title: '神秘包裹', description: '星际快递员送来一个没有寄件人的包裹，里面是你最爱吃的糖果，可追踪记录显示它来自一艘早已注销的货船。你被安保请去喝了两小时茶。', effects: { luck: 2, charisma: -1 }, exp: 11, weight: 1 },
  { id: 'solar-storm-warning', title: '太阳风暴预警', description: '太阳风暴预警拉响，全站人员挤进防辐射舱。你给孩子们讲了个关于太阳的童话，讲完掌声雷动。', effects: { charisma: 2, intelligence: 1 }, exp: 10, weight: 1 },
  { id: 'station-anniversary', title: '空间站周年庆', description: '空间站建成五十周年庆典上，站长点名感谢你上周修的空气循环泵，全场举杯，你的名字被记进了站志。', effects: { charisma: 2, luck: 1 }, exp: 10, weight: 1 },
  { id: 'probe-photo', title: '深空照片', description: '深空探测器传回一张照片：星云中心静静悬浮着一座看起来像城市的巨大结构。研究组邀请你参与分析。', effects: { intelligence: 3, luck: 1 }, exp: 12, weight: 1 },
  { id: 'quantum-comms-test', title: '量子通讯实验', description: '你报名当量子通讯实验的志愿者，隔着半个星域和地球的科学家打了声招呼。实验成功后你收到一枚纪念徽章。', effects: { intelligence: 2, luck: 1 }, exp: 12, weight: 1 },
  { id: 'space-climbing-wall', title: '太空攀岩墙', description: '空间站的攀岩墙模拟了陨石坑岩壁，你在零重力下攀到顶点按下计时器，成绩排进本站前十。', effects: { strength: 2, agility: 1 }, exp: 11, weight: 1 },
  { id: 'galaxy-mart-sale', title: '星际超市大促', description: '星际超市周年庆大促，你抢到一台半价的家用反应堆清洁器，收银机器人还送你一张抽奖券。', effects: { luck: 2, intelligence: 1 }, exp: 11, weight: 1 },
  { id: 'vr-meditation', title: '虚拟冥想舱', description: '虚拟冥想舱里播放的「深空日出」让你看了十分钟，出来时神清气爽，技师说这趟体验能顶八小时睡眠。', effects: { vitality: 2, intelligence: 1 }, exp: 10, weight: 1 },
  { id: 'discount-augment', title: '打折义体', description: '义体商店半价清仓，你买了副翻新神经手套，戴上后反应快了零点几秒，可一到阴天它就开始随机抖动——卖家说这叫「复古魅力」。', effects: { agility: 2, luck: -2 }, exp: 12, weight: 1 },
  { id: 'stray-ship-dock', title: '漂流货船', description: '一艘无人驾驶的货船漂到你的航线附近，舱门大开，货舱里堆满来历不明的矿石，船载日志却显示它已空转三十年。', effects: { luck: 3, intelligence: 2 }, exp: 14, minLevel: 2, weight: 1 },
  { id: 'pirate-scanner', title: '海盗扫描', description: '传感器捕捉到一道来自海盗船的扫描信号，对方正沿着你的航迹逼近。你必须在被锁定前改变航线，或者虚张声势吓退他们。', effects: { agility: 3, intelligence: 2 }, exp: 14, minLevel: 2, weight: 1 },
  { id: 'ion-storm', title: '离子风暴', description: '前方航线突遇离子风暴，通讯中断、导航失灵。你凭手动驾驶穿过风暴眼，仪表盘在出口处才重新亮起来。', effects: { agility: 4, luck: 2 }, exp: 15, minLevel: 2, weight: 1 },
  { id: 'smuggler-bay', title: '走私货舱', description: '例行盘点时，你在货舱深处发现一批未申报的冷冻生物样本。船长把决定权交给你：上报，还是当作没看见。', effects: { intelligence: 3, charisma: 2 }, exp: 14, minLevel: 2, weight: 1 },
  { id: 'derelict-board', title: '登舰调查', description: '你奉命登上一艘漂流已久的废弃战舰，残骸深处的 AI 残留请求你帮它完成清单上最后一项任务：把阵亡船员的名单送回家。', effects: { intelligence: 4, luck: 1 }, exp: 15, minLevel: 2, weight: 1 },
  { id: 'asteroid-chase', title: '小行星追逐', description: '一颗失控的采矿无人机拖着一串矿石冲进你的航道，你在碎片雨里贴近它，用磁力钩把它逼停下来。', effects: { agility: 3, strength: 2 }, exp: 14, minLevel: 2, weight: 1 },
  { id: 'relay-sabotage', title: '中继站破坏', description: '通讯中继站信号异常，你排查后发现有人改写了转发代码，正把站内流量悄悄引向一个未知坐标。', effects: { intelligence: 4, charisma: 1 }, exp: 15, minLevel: 2, weight: 1 },
  { id: 'space-station-blackout', title: '空间站停电', description: '空间站突然全站停电，你在应急灯下组织几十名乘客有序转移到备用舱段，直到备用电源重新上线。', effects: { charisma: 3, agility: 2 }, exp: 15, minLevel: 2, weight: 1 },
  { id: 'hull-leak', title: '舱壁泄漏', description: '一块微陨石击穿货舱舱壁，失压警报炸响。你顶着呼啸的气流抢修，用一块备用装甲板堵住了缺口。', effects: { strength: 3, vitality: 2 }, exp: 14, minLevel: 2, weight: 1 },
  { id: 'stowaway', title: '偷渡者', description: '气闸舱角落里蜷着一个偷渡的少年，怀里抱着一台写满加密代码的旧电脑。他抬起头，眼神像一头受惊的小兽。', effects: { charisma: 2, intelligence: 3 }, exp: 14, minLevel: 2, weight: 1 },
  { id: 'nav-drift', title: '航向漂移', description: '自动驾驶突然把船带向一颗未标注的矮行星，警报一声接一声。你抢在坠毁前切回手动接管，把航向掰了回来。', effects: { intelligence: 3, agility: 2 }, exp: 14, minLevel: 2, weight: 1 },
  { id: 'quarantine-alert', title: '检疫警报', description: '港口检疫系统把整艘船标记为「疑似污染源」，你配合检疫官逐舱排查，最终证明只是一次传感器误报。', effects: { charisma: 3, luck: 2 }, exp: 15, minLevel: 2, weight: 1 },
  { id: 'solar-sail-race', title: '光帆竞速', description: '你报名参加光帆船竞速赛，在太阳风的推动下穿越一片小行星带，最后半圈反超了那位老牌冠军。', effects: { agility: 3, luck: 2 }, exp: 15, minLevel: 2, weight: 1 },
  { id: 'abandoned-station', title: '废弃空间站', description: '废弃空间站的档案室里封存着一批研究数据，数据尾部似乎藏着某个被刻意掩盖的实验记录。', effects: { intelligence: 4, luck: 2 }, exp: 16, minLevel: 2, weight: 1 },
  { id: 'cyber-heist', title: '数据窃案', description: '有人雇你潜入一颗卫星的数据库盗取加密档案。得手后你才发现，档案里的名单全是你的旧同事。', effects: { intelligence: 4, agility: 3 }, exp: 16, minLevel: 3, weight: 1 },
  { id: 'colony-uprising', title: '殖民地抗议', description: '矿区殖民地爆发抗议，双方在气闸门前对峙。你在中间斡旋了一整夜，促成了有条件停火谈判。', effects: { charisma: 4, intelligence: 2 }, exp: 17, minLevel: 3, weight: 1 },
  { id: 'rogue-ai', title: '失控 AI', description: '货船的舱载 AI 突然锁死所有舱门，声称要「保护」船上的货物。你通过一段对话让它主动解除了锁定。', effects: { charisma: 3, intelligence: 3 }, exp: 17, minLevel: 3, weight: 1 },
  { id: 'nanite-plague', title: '纳米瘟疫', description: '空间站爆发纳米机器人感染，感染者正蚕食站内金属结构。你参与封锁疫区，在结构坍塌前切断了感染源。', effects: { intelligence: 4, vitality: 2 }, exp: 17, minLevel: 3, weight: 1 },
  { id: 'quantum-bank', title: '量子银行劫案', description: '量子银行发生「存款凭空消失」事件，你协助追查，发现那是来自平行时间线的一次交叉转账。', effects: { intelligence: 5, luck: 2 }, exp: 18, minLevel: 3, weight: 1 },
  { id: 'deep-space-radio', title: '深空电台', description: '你在深空截获一段规律信号，破译后是一封求救信——发信方是颗即将被潮汐撕碎的行星上的最后一座城市。', effects: { intelligence: 3, luck: 3 }, exp: 17, minLevel: 3, weight: 1 },
  { id: 'cyborg-market', title: '义体黑市', description: '义体黑市有人兜售「全新未拆封」的军用神经接口，你认出那是上周失窃的货，不动声色地报了警。', effects: { intelligence: 3, charisma: 2 }, exp: 16, minLevel: 3, weight: 1 },
  { id: 'reality-glitch', title: '现实故障', description: '空间站的窗户突然倒映出另一个时空的你，他隔着玻璃朝你打了一串手势——像是在警告什么。', effects: { intelligence: 4, luck: 2 }, exp: 17, minLevel: 3, weight: 1 },
  { id: 'oxygen-trade', title: '氧气黑市', description: '氧气黑市的价格高得离谱，你绕了三层中间商，用一批废旧电池换到了够全站用一周的氧气。', effects: { charisma: 3, agility: 2 }, exp: 16, minLevel: 3, weight: 1 },
  { id: 'engine-overload', title: '引擎过载', description: '跃迁前三十秒，主引擎突然过载。你冲进机舱手动排空燃料管路，保住了一船人和整条航线。', effects: { strength: 3, intelligence: 3 }, exp: 17, minLevel: 3, weight: 1 },
  { id: 'xenobiologist', title: '外星生物学家', description: '研究站里，一位外星生物学家正为濒危标本发愁。你帮它抢救了最后一枚卵，它回赠你一份矿藏丰富的星域坐标。', effects: { intelligence: 3, luck: 3 }, exp: 17, minLevel: 3, weight: 1 },
  { id: 'titan-signal', title: '泰坦信号', description: '土卫六的冰层下传来规律的敲击声，你随勘探队下潜，在甲烷冰层深处发现一座由冰砖砌成的古代建筑。', effects: { intelligence: 4, agility: 2 }, exp: 18, minLevel: 3, weight: 1 },
  { id: 'refugee-fleet', title: '难民船队', description: '一支失去家园的难民船队请求在你负责的港口停靠，你顶住多方压力，为它们争取到了临时庇护权。', effects: { charisma: 4, luck: 2 }, exp: 18, minLevel: 3, weight: 1 },
  { id: 'megastructure-rise', title: '巨构苏醒', description: '沉睡千年的轨道巨构突然苏醒，能源核心沿古老轨道重新点火，整个星域都收到了它的广播。你被推举为代表，站上它的应答平台。', effects: { charisma: 4, intelligence: 4 }, exp: 21, minLevel: 4, weight: 1 },
  { id: 'star-bridge', title: '星桥贯通', description: '一座连接两个星系的人工星桥骤然贯通，桥的另一端传来陌生文明的问候——而你的飞船正停在桥口。', effects: { intelligence: 5, luck: 3 }, exp: 22, minLevel: 4, weight: 1 },
  { id: 'bioship', title: '生物星舰', description: '深空漂来一艘血肉与合金交织的生物星舰，它的「心脏」仍在搏动，向你发出共生的邀请。', effects: { vitality: 4, intelligence: 3 }, exp: 20, minLevel: 4, weight: 1 },
  { id: 'dyson-swarm', title: '戴森云海', description: '你驶入一片正在成形的戴森云海，数以万计的采能卫星正缓缓包裹一颗恒星。云海的调度者请你仲裁一场持续百年的资源争端。', effects: { charisma: 4, intelligence: 4 }, exp: 23, minLevel: 5, weight: 1 },
  { id: 'time-anomaly', title: '时间异常', description: '你的飞船被卷入一场时间异常，同一天循环了十七次。你在最后一次循环里找到了破局的钥匙，也看清了那个一直在幕后的人。', effects: { intelligence: 5, agility: 3 }, exp: 24, minLevel: 5, weight: 1 },
  { id: 'planet-birth', title: '行星诞生', description: '一团年轻星云正在孕育新的行星，你驾驶飞船穿过尘埃盘，抢在所有观测站之前采集到第一手数据——这段影像将被载入天文史。', effects: { intelligence: 5, luck: 4 }, exp: 23, minLevel: 5, weight: 1 },
  { id: 'galactic-council', title: '银河议会', description: '银河议会的仲裁席空出一个位置，七个文明联名推举你出席那场决定星域命运的投票。你走进穹顶大厅时，所有目光都转向了你。', effects: { charisma: 5, luck: 3 }, exp: 26, minLevel: 6, weight: 1 },
]
