/**
 * 都市主题：新增事件。
 */
import type { AdventureEvent } from '../themes.js'

export const URBAN_NEW_EVENTS: readonly AdventureEvent[] = [
  // ---------- 日常（53）----------
  { id: 'morning-run', title: '晨跑偶遇', description: '清晨六点的滨江步道，一个跑姿标准的老太太把你远远甩在身后。她回头冲你笑：「年轻人，别急，呼吸比速度重要。」', effects: { vitality: 3, agility: 1 }, exp: 10, weight: 1 },
  { id: 'seat-giving', title: '地铁让座', description: '早高峰地铁里，你刚坐下就瞥见一位孕妇扶着栏杆。你起身让座，她道谢时塞给你一颗糖——是橘子味的。', effects: { charisma: 2, luck: 1 }, exp: 9, weight: 1 },
  { id: 'cold-coffee', title: '打翻的咖啡', description: '赶路的你被迎面跑来的外卖员撞翻咖啡，褐色污渍在衬衫上迅速晕开。他连声道歉，你看着手表只能苦笑——今天注定狼狈开场。', effects: { luck: -2, agility: 2 }, exp: 9, weight: 1 },
  { id: 'shared-bike', title: '共享单车', description: '最后一辆共享单车被人抢先扫码，你正要放弃，旁边的保洁阿姨指了指绿化带：「那辆轮子有点瘪，补口气就能骑。」', effects: { agility: 2, luck: 1 }, exp: 10, weight: 1 },
  { id: 'parcel-station', title: '快递驿站', description: '驿站小哥把你的快递翻了个底朝天，最后从纸箱夹层里抽出一个小包裹：「你买的种子，老板夹带私货了。」', effects: { luck: 2 }, exp: 9, weight: 1 },
  { id: 'checkout-change', title: '收银台零钱', description: '便利店收银台前排着长队，你摸遍口袋只差五毛。身后的陌生大叔递来一枚硬币：「先垫着，下次你请我。」', effects: { charisma: 2 }, exp: 10, weight: 1 },
  { id: 'print-shop', title: '打印店', description: '打印店老板看着你递来的简历啧啧称奇：「这排版十年没见过了。」他随手帮你调了版式，还说「细节是门面」。', effects: { intelligence: 2, charisma: 1 }, exp: 11, weight: 1 },
  { id: 'freight-elevator', title: '货梯搬运', description: '写字楼的客梯检修，你只能和搬家师傅挤货梯。他递给你一截绳子：「搭把手，省得我跑两趟。」你抱着纸箱，听了一路他的奋斗史。', effects: { strength: 3 }, exp: 11, weight: 1 },
  { id: 'taxi-rain', title: '雨天的士', description: '暴雨突至，你站在路边等车，一辆刚熄火的出租车缓缓停在你面前。司机摇下车窗：「顺路，上来吧，这雨一时半会儿停不了。」', effects: { luck: 2, vitality: 1 }, exp: 10, weight: 1 },
  { id: 'pancake-stall', title: '煎饼摊', description: '街角煎饼摊的阿姨记得你不吃香菜，摊饼时手速快到看不清。她一边翻面一边念叨：「年轻人，早餐不吃好，一天都没劲。」', effects: { vitality: 2, charisma: 1 }, exp: 10, weight: 1 },
  { id: 'library-seat', title: '图书馆占座', description: '图书馆自习区一座难求，你发现靠窗的位置被人用一本《城市交通规划》占了。你正要离开，书的主人抱着咖啡回来：「坐吧，我一会儿就走。」', effects: { intelligence: 3 }, exp: 11, weight: 1 },
  { id: 'gym-barbell', title: '健身房加片', description: '健身房角落，一个瘦高个盯着杠铃片发愁。你走过去帮他加了两片，他连连道谢，说下个月要参加公司体能测试。', effects: { strength: 3, charisma: 1 }, exp: 11, weight: 1 },
  { id: 'market-haggle', title: '菜场砍价', description: '菜市场的鱼摊前，你学着旁边大妈砍价，摊主摆手：「行行行，给你抹个零。」大妈冲你竖大拇指：「小伙子，有前途。」', effects: { charisma: 3 }, exp: 10, weight: 1 },
  { id: 'night-runner', title: '深夜跑腿', description: '你接了一单深夜跑腿，把药送到独居老人楼下。老人多塞给你一盒牛奶：「这么晚还跑，路上小心。」路灯把你的影子拉得很长。', effects: { agility: 2, charisma: 2 }, exp: 12, weight: 1 },
  { id: 'rooftop-break', title: '楼顶放风', description: '午休时你溜上楼顶，看见隔壁部门的老张在偷偷打太极。他招招手：「别告诉别人，这是我一天里最清静的时候。」', effects: { vitality: 2, intelligence: 1 }, exp: 10, weight: 1 },
  { id: 'roommate-dinner', title: '合租晚餐', description: '合租室友难得下厨，端出一锅卖相可疑的番茄牛腩。你硬着头皮尝了一口，居然意外地好吃，他得意地挑眉：「深藏不露吧。」', effects: { charisma: 2, vitality: 1 }, exp: 10, weight: 1 },
  { id: 'laptop-repair', title: '修电脑', description: '电脑在汇报前两小时蓝屏，楼下维修店的小哥十分钟就找到了病根。他边拧螺丝边说：「下次别把咖啡放主机旁边。」', effects: { intelligence: 3 }, exp: 11, weight: 1 },
  { id: 'team-building', title: '拔河比赛', description: '公司团建拔河，你被安排在队尾压阵。绳子勒得掌心发红，但最后一下你咬紧牙关，把对面拖过了线——全队把你举了起来。', effects: { strength: 3, charisma: 1 }, exp: 13, weight: 1 },
  { id: 'overtime-snack', title: '加班夜宵', description: '凌晨一点的写字楼，你盯着屏幕眼皮打架。隔壁工位的同事扔来一包辣条：「垫垫肚子，再战最后一轮。」你嚼着辣条，忽然觉得夜也没那么难熬。', effects: { vitality: -2, intelligence: 3 }, exp: 11, weight: 1 },
  { id: 'last-train', title: '末班地铁', description: '末班地铁空空荡荡，你靠在车门边打盹。报站声响起时你猛地惊醒——还好，离你的站还有三站。', effects: { luck: 2, agility: 1 }, exp: 10, weight: 1 },
  { id: 'pet-cafe', title: '猫咖打工', description: '周末你在猫咖帮忙，一只布偶猫赖在你腿上不走。老板娘笑着拍照：「它可是我们店的招牌，你运气不错。」', effects: { charisma: 3, luck: 1 }, exp: 11, weight: 1 },
  { id: 'street-singer', title: '街头歌手', description: '天桥下，一个背着吉他的歌手唱完一首老歌，摘下帽子递到你面前。你投了两枚硬币，他朝你点头致意，又弹起了下一首。', effects: { charisma: 1, luck: 1 }, exp: 9, weight: 1 },
  { id: 'green-light', title: '红灯冲刺', description: '你掐着秒表过马路，绿灯还剩三秒。你小跑两步，在红灯亮起的瞬间踏上对面台阶，身后传来骑车大爷的喊声：「小伙子，腿脚不错啊！」', effects: { agility: 3 }, exp: 10, weight: 1 },
  { id: 'courier-bonus', title: '快递员叔叔', description: '你帮楼下的快递员按住电梯，他道谢后从兜里掏出一个橘子塞给你：「刚收的，甜得很。」橘子皮上还带着阳光的温度。', effects: { charisma: 2, luck: 1 }, exp: 10, weight: 1 },
  { id: 'lost-found', title: '失物招领', description: '失物招领处，你找到自己丢了一周的耳机，旁边还躺着一把被认领过的旧伞。管理员说：「每天都有东西被忘在这里，也有东西被找回。」', effects: { luck: 2 }, exp: 9, weight: 1 },
  { id: 'night-jog', title: '夜跑路线', description: '你换了条夜跑路线，意外发现河边新修了一段步道。凉风习习，只有虫鸣和你自己的脚步声陪着你。', effects: { vitality: 3 }, exp: 10, weight: 1 },
  { id: 'secondhand-book', title: '旧书夹页', description: '旧书店里，你翻开一本泛黄的《城市漫游指南》，一张三十年前的公交车票从书页间滑落，票根上的站名早已改了几轮。', effects: { intelligence: 3, luck: 1 }, exp: 12, weight: 1 },
  { id: 'breakfast-stall', title: '早餐摊', description: '常去的早餐摊今天多送了你一根油条，老板说：「看你天天来，是个实诚人。」油条炸得金黄，咬下去满口酥脆。', effects: { vitality: 2 }, exp: 9, weight: 1 },
  { id: 'bulb-change', title: '换灯泡', description: '合租房的客厅灯忽明忽暗，你踩着凳子拧下旧灯泡，换上新的。亮起来的瞬间，整间屋子都暖了几分。', effects: { strength: 2, intelligence: 1 }, exp: 10, weight: 1 },
  { id: 'sink-repair', title: '修水管', description: '厨房水龙头滴水，你照着教程拆开换上垫圈，居然一次成功。室友在门口鼓掌：「以后家里的活都归你了。」', effects: { strength: 2, intelligence: 2 }, exp: 11, weight: 1 },
  { id: 'mock-interview', title: '模拟面试', description: '朋友拉你当模拟面试官，你随口问的问题居然难住了他。他认真记下笔记：「你这一问，我回去得准备三天。」', effects: { intelligence: 2, charisma: 2 }, exp: 11, weight: 1 },
  { id: 'moving-help', title: '帮搬家', description: '隔壁新搬来的邻居一个人扛着沙发，你二话不说搭了把手。两人气喘吁吁地把家具摆好，他递给你一瓶冰水：「以后常来坐。」', effects: { strength: 3, charisma: 1 }, exp: 11, weight: 1 },
  { id: 'washer-trick', title: '洗衣机', description: '公共洗衣房，你的衣服和别人的缠在一起。你蹲下来理了十分钟，把它们分开叠好，正好遇见衣服主人回来道谢。', effects: { intelligence: 2, charisma: 1 }, exp: 10, weight: 1 },
  { id: 'blackout', title: '停电夜', description: '小区突然停电，你摸黑下楼买蜡烛，便利店老板笑着送你一支手电筒：「老小区，常事儿，备着点。」', effects: { luck: -1, vitality: 2 }, exp: 9, weight: 1 },
  { id: 'guard-talk', title: '门卫师傅', description: '深夜下班，门卫师傅给你留了盏灯。他笑着说：「我看你这灯亮得最晚，年轻人，拼是好事，也要顾着身体。」', effects: { charisma: 2, vitality: 1 }, exp: 10, weight: 1 },
  { id: 'bus-card', title: '公交卡', description: '公交卡余额不足，你翻遍口袋没找到零钱。身后的大姐递过两块钱：「先上车，别耽误了上班。」你记下她的号码，第二天把钱还了。', effects: { luck: 2, charisma: 1 }, exp: 10, weight: 1 },
  { id: 'dead-phone', title: '手机没电', description: '手机在关键通话前一刻没电，你四处借充电宝未果，只能手写记录下所有要点。没想到，这反而让你记住了全部细节。', effects: { intelligence: 3, luck: -1 }, exp: 11, weight: 1 },
  { id: 'lost-in-city', title: '城市迷路', description: '你跟着导航钻进一条从没走过的小巷，结果误入一片老居民区，墙上的爬山虎绿得发亮，像另一个世界。', effects: { agility: 2, intelligence: 1 }, exp: 10, weight: 1 },
  { id: 'flea-market', title: '跳蚤市场', description: '周末跳蚤市场，你在一个旧物摊前蹲了半天，淘到一个八成新的机械键盘。摊主说：「识货的人不多，给你了。」', effects: { luck: 3 }, exp: 11, weight: 1 },
  { id: 'stairs-climb', title: '爬楼梯', description: '电梯检修，你一口气爬了十八层。到顶楼时虽然腿软，但推开楼梯间的门，迎面就是城市的晨光。', effects: { vitality: 3, agility: 1 }, exp: 11, weight: 1 },
  { id: 'chestnut-stall', title: '糖炒栗子', description: '深秋傍晚，糖炒栗子的香气从街角飘来。你买了一份，老板娘多抓了一把：「刚出锅的，热乎着，趁早吃。」', effects: { vitality: 2, luck: 1 }, exp: 10, weight: 1 },
  { id: 'barber-chat', title: '理发店', description: '理发师一边剪发一边和你聊起这座城市的变迁，他说他在这条街上干了二十年，「看着一栋栋楼长起来」。', effects: { charisma: 2, intelligence: 1 }, exp: 10, weight: 1 },
  { id: 'supermarket-line', title: '超市结账', description: '超市排队结账，前面的大爷掏出一大把硬币慢慢数。你没有催促，反而帮他把硬币码整齐，他回头冲你咧嘴笑。', effects: { charisma: 2, luck: 1 }, exp: 10, weight: 1 },
  { id: 'vending-machine', title: '贩卖机', description: '自动贩卖机吞了你的钱却没有掉饮料。你拍了两下，机器抖了抖，吐出一瓶饮料还多送了一罐——像是道歉。', effects: { luck: 2 }, exp: 9, weight: 1 },
  { id: 'locker-hunt', title: '快递柜', description: '快递柜的柜门卡住了，你蹲下来捣鼓半天，终于撬开一条缝。取出的包裹完好无损，你长舒一口气，像完成了一场微型救援。', effects: { agility: 2, intelligence: 1 }, exp: 10, weight: 1 },
  { id: 'night-class', title: '夜校英语', description: '你在社区夜校报了英语课，同桌是个五十多岁的阿姨，笔记记得比你还工整。她说：「活到老学到老，不能掉队。」', effects: { intelligence: 3, charisma: 1 }, exp: 11, weight: 1 },
  { id: 'jam-podcast', title: '堵车播客', description: '高架堵成停车场，你打开收藏已久的播客，听完一期关于城市地下管网的节目。红灯变绿时，你竟觉得这段堵车不算浪费。', effects: { intelligence: 2, luck: -2 }, exp: 10, weight: 1 },
  { id: 'chess-old-men', title: '棋摊观战', description: '公园棋摊，两位大爷为一盘残局争得面红耳赤。你旁观半天，忍不住指了一步，结果真成了妙手。大爷拍你肩膀：「小子，有点东西。」', effects: { intelligence: 3, charisma: 1 }, exp: 11, weight: 1 },
  { id: 'blind-date', title: '相亲局', description: '相亲安排在商场咖啡厅，对方迟到了半小时，却在见面时递给你一杯你最爱的美式：「路上堵，先赔罪。」', effects: { charisma: 2, luck: 1 }, exp: 10, weight: 1 },
  { id: 'wallet-return', title: '拾金不昧', description: '你在共享单车车筐里捡到一个钱包，按着证件地址送回去。失主塞给你两百块，你没收，只留了一句「下次小心」。', effects: { luck: 3, charisma: 1 }, exp: 12, weight: 1 },
  { id: 'weather-warning', title: '天气预报', description: '你出门前随手看了天气预报，果断带了伞。傍晚果然暴雨倾盆，地铁口挤满躲雨的人，只有你从容撑开伞。', effects: { luck: 2, intelligence: 1 }, exp: 10, weight: 1 },
  { id: 'window-seat', title: '靠窗座位', description: '公交车上你抢到靠窗的座位，阳光正好洒进来。你戴上耳机看窗外掠过的街景，忽然觉得这座忙碌的城市也有温柔的一面。', effects: { vitality: 2, luck: 1 }, exp: 10, weight: 1 },
  { id: 'newsstand', title: '报刊亭', description: '街角报刊亭的老板给你留了一份绝版杂志：「上次你说想找，我记着呢。」杂志泛黄，扉页上还有前任主人的签名。', effects: { intelligence: 2, luck: 1 }, exp: 11, weight: 1 },
  // ---------- 冒险（28）----------
  { id: 'midnight-radio', title: '深夜电台', description: '凌晨的收音机里传来一个陌生频段，主播声音沙哑，念着只有你听过的街道名。他最后说：「如果你在听，明天老地方见。」', effects: { intelligence: 3, luck: 2 }, exp: 14, minLevel: 2, weight: 1 },
  { id: 'old-district', title: '拆迁前夜', description: '老城区拆迁前夜，整条街的居民在巷口摆了长桌宴。你路过时被拉进座位，一位大爷举杯：「敬这条街，也敬路过的有缘人。」', effects: { charisma: 3, vitality: 2 }, exp: 15, minLevel: 2, weight: 1 },
  { id: 'night-taxi', title: '夜车司机', description: '你打了一辆午夜出租车，司机绕着环线开，讲起这座城市凌晨的秘密：「这个点还在路上的人，都有故事。」到站时他没收零头。', effects: { charisma: 2, intelligence: 2 }, exp: 14, minLevel: 2, weight: 1 },
  { id: 'rooftop-cafe', title: '顶楼咖啡', description: '朋友带你爬上一栋老楼的顶层，那里藏着一家只开周末的咖啡馆。老板说：「这里能看到这座城市最真实的轮廓。」', effects: { charisma: 2, luck: 2 }, exp: 15, minLevel: 2, weight: 1 },
  { id: 'city-marathon', title: '城市半马', description: '你临时顶替朋友参加城市半马，起跑时双腿发软，却在最后五公里被沿途观众的加油声推着冲过终点线。', effects: { vitality: 4, agility: 2 }, exp: 16, minLevel: 2, weight: 1 },
  { id: 'ghost-station', title: '幽灵站台', description: '地铁末班车在一个从没报过站的站台停了三十秒，车门打开又关上。同车厢的老太太说：「这是老站，早废弃了，只有末班车还记得它。」', effects: { intelligence: 4, luck: 1 }, exp: 15, minLevel: 2, weight: 1 },
  { id: 'archive-room', title: '档案室', description: '你在公司档案室找一份旧合同，无意间翻出一卷八十年代的城市规划图。图上标注的轻轨线路，至今仍未建成。', effects: { intelligence: 4 }, exp: 14, minLevel: 2, weight: 1 },
  { id: 'old-bookshop', title: '旧书店老板', description: '旧书店老板认出你常来，从柜台下抽出一本绝版诗集：「送你，这书就该被年轻人翻旧。」扉页上写着他的笔名。', effects: { intelligence: 3, charisma: 1 }, exp: 14, minLevel: 2, weight: 1 },
  { id: 'ring-found', title: '戒指失主', description: '你在公园长椅缝里捡到一枚刻着名字的戒指，费尽周折找到失主——是一对结婚四十年的老夫妻。老太太握着你的手久久不放。', effects: { luck: 4, charisma: 2 }, exp: 16, minLevel: 2, weight: 1 },
  { id: 'all-night-library', title: '通宵自习室', description: '通宵自习室里，对面座位的人递来一张纸条：「你翻书的声音很好听，像在给这座城市守夜。」你抬头，只看见一个背影。', effects: { intelligence: 3, luck: 2 }, exp: 15, minLevel: 2, weight: 1 },
  { id: 'night-guard', title: '夜班保安', description: '你加班到深夜，写字楼的夜班保安陪你走完最后一层楼。他说他在这栋楼守了十年，「见过凌晨四点的天花板，也见过凌晨四点的你」。', effects: { vitality: 2, strength: 2 }, exp: 14, minLevel: 2, weight: 1 },
  { id: 'warehouse-shift', title: '快递仓库', description: '朋友拉你顶一班快递分拣，凌晨的仓库灯火通明。你搬了一夜货，手臂酸到抬不起来，却见识了这座城市物流的「心跳」。', effects: { strength: 4, vitality: 2 }, exp: 16, minLevel: 2, weight: 1 },
  { id: 'street-magic', title: '街头魔术', description: '街头艺人把一枚硬币变进你外套口袋，你掏出来时，硬币上多了一个陌生的印记。他眨眨眼：「这是这座城市给你的纪念品。」', effects: { luck: 4, charisma: 1 }, exp: 15, minLevel: 2, weight: 1 },
  { id: 'stray-cat', title: '楼道流浪猫', description: '楼道里新来了一只流浪猫，你喂了它三天，它开始在你门口守着。室友说：「它挑中了这层楼，也挑中了你。」', effects: { charisma: 3, luck: 1 }, exp: 14, minLevel: 2, weight: 1 },
  { id: 'light-show', title: '灯光秀', description: '城市地标大楼亮起灯光秀，全城的人都在仰头。你站在人群里，忽然觉得这千万盏灯里，也有一盏是你亮着的。', effects: { charisma: 3, luck: 2 }, exp: 16, minLevel: 3, weight: 1 },
  { id: 'underpass-piano', title: '地下琴声', description: '地下通道里传来钢琴声，一个穿工装的年轻人弹着《致爱丽丝》。路人们放慢脚步，有人往琴盒里放了张纸条，写着「明天也来」。', effects: { charisma: 3, intelligence: 2 }, exp: 17, minLevel: 3, weight: 1 },
  { id: 'abandoned-factory', title: '废弃工厂', description: '你跟着摄影爱好者钻进废弃工厂，锈迹斑斑的机器在夕照下像沉默的巨兽。有人在墙上发现一行字：「这里曾养活半座城。」', effects: { agility: 3, intelligence: 2 }, exp: 16, minLevel: 3, weight: 1 },
  { id: 'night-bookstore', title: '深夜书店', description: '深夜的书店亮着灯，店主说这家店二十四小时不打烊。你买下一本《城市怪谈》，结账时他提醒：「第三篇，别在熄灯后读。」', effects: { intelligence: 4, luck: 1 }, exp: 17, minLevel: 3, weight: 1 },
  { id: 'rooftop-garden', title: '楼顶菜园', description: '你发现对面楼顶藏着一片菜园，种菜的大叔隔空喊话：「我这儿番茄熟了，分你几个。」绳子吊下来的篮子里，番茄还带着晨露。', effects: { vitality: 3, charisma: 2 }, exp: 16, minLevel: 3, weight: 1 },
  { id: 'city-cycling', title: '环城骑行', description: '周末你骑共享单车环城，从老城区骑到新城区，像一口气翻完这座城市的相册。晚上腿是软的，心里是满的。', effects: { vitality: 4, agility: 3 }, exp: 17, minLevel: 3, weight: 1 },
  { id: 'flea-treasure', title: '旧货淘金', description: '旧货市场的地摊上，你花二十块买下一台坏掉的收音机。回家修好后，竟收到一段几十年前的城市广播。', effects: { luck: 4, intelligence: 2 }, exp: 17, minLevel: 3, weight: 1 },
  { id: 'rescue-help', title: '江湖救急', description: '电梯里有人突发不适，你背起他冲下楼梯，跑过三条街送到医院。医生说再晚十分钟就危险了，家属在你面前哽咽着道谢。', effects: { strength: 4, vitality: 2 }, exp: 17, minLevel: 3, weight: 1 },
  { id: 'metro-drill', title: '地铁演练', description: '你正好赶上地铁安全演练，跟着工作人员学会了破窗、灭火、疏散。演练结束，负责人拍了拍你：「记住，关键时刻这些能救命。」', effects: { agility: 3, intelligence: 2 }, exp: 16, minLevel: 3, weight: 1 },
  { id: 'city-walk', title: '城市漫游', description: '你关了导航，随性在城市里乱走，钻小巷、过天桥、逛菜场。傍晚时发现自己走了两万步，也捡回了一兜子故事。', effects: { agility: 3, luck: 2 }, exp: 16, minLevel: 3, weight: 1 },
  { id: 'late-night-porridge', title: '深夜粥铺', description: '午夜粥铺只卖白粥和小菜，老板说：「这个点来喝粥的，都是心里有事的人。」你喝完一碗，胃暖了，心也静了。', effects: { vitality: 3, intelligence: 1 }, exp: 15, minLevel: 3, weight: 1 },
  { id: 'old-doctor', title: '老中医', description: '你陪朋友看老中医，老大夫顺手给你把了把脉：「熬夜太多，气血亏。」他开了张方子，还叮嘱你「身体是透支不起的」。', effects: { vitality: 3, intelligence: 2 }, exp: 16, minLevel: 3, weight: 1 },
  { id: 'street-interview', title: '街头采访', description: '一个学生记者拦住你采访「你眼中的这座城市」，你随口说的几句话被剪成短片，意外在本地频道播出，朋友们纷纷截图给你。', effects: { charisma: 4, intelligence: 1 }, exp: 17, minLevel: 3, weight: 1 },
  { id: 'fire-drill', title: '消防演习', description: '小区消防演习，你自告奋勇当楼长，扛着灭火器挨家敲门演练。演习结束，物业阿姨塞给你一箱矿泉水：「辛苦啦，楼长。」', effects: { agility: 3, charisma: 2 }, exp: 16, minLevel: 3, weight: 1 },
  // ---------- 史诗（8）----------
  { id: 'city-blackout', title: '全城停电', description: '一场罕见的大停电让整座城市陷入黑暗，你却意外发现，黑暗中的人们反而都走出了家门，在广场上互相照亮。', effects: { luck: 5, charisma: 3 }, exp: 20, minLevel: 4, weight: 1 },
  { id: 'underground-river', title: '地下暗河', description: '城市管道检修时，你跟着师傅爬进地下，发现一条被掩埋百年的暗河仍在静静流淌。河岸的石壁上，刻着这座城市最初的名字。', effects: { intelligence: 5, luck: 2 }, exp: 21, minLevel: 4, weight: 1 },
  { id: 'bridge-night', title: '跨江夜跑', description: '跨江大桥封桥检修，你赶在最后一晚跑步上桥。江风猎猎，你站在桥中央，看两岸灯火连成一条流动的银河。', effects: { strength: 5, vitality: 3 }, exp: 21, minLevel: 4, weight: 1 },
  { id: 'neon-deep', title: '霓虹深处', description: '你误入一条霓虹招牌最密集的老街，街尾一家只亮一盏灯的店。老板说：「这条街的灯，都是为迷路的人留的。」', effects: { charisma: 4, luck: 3 }, exp: 20, minLevel: 4, weight: 1 },
  { id: 'typhoon-night', title: '台风夜', description: '台风登陆夜，你披着雨衣帮小区加固门窗、搬运沙袋。凌晨风最大的时候，全楼的灯都亮了，像在给彼此打气。', effects: { strength: 5, vitality: 4 }, exp: 22, minLevel: 5, weight: 1 },
  { id: 'midnight-library', title: '子夜图书馆', description: '城市图书馆的深夜闭馆日，管理员破例让你留到午夜。钟声敲响时，书架深处传来翻页声——你循声而去，看见一本自己翻开自己读的书。', effects: { intelligence: 6, luck: 2 }, exp: 23, minLevel: 5, weight: 1 },
  { id: 'clock-tower', title: '钟楼之约', description: '老钟楼停摆三十年，你凭着旧档案里的图纸，一步步爬上去修好了齿轮。整点时分，钟声第一次响起，全城的人都抬头看了看天。', effects: { intelligence: 5, strength: 3 }, exp: 23, minLevel: 5, weight: 1 },
  { id: 'city-otherside', title: '城市背面', description: '凌晨三点，你误乘了一辆开往城市「背面」的夜车，那里的人用另一套时间生活。黎明前你回到自己熟悉的街道，口袋里多了一枚不属于这个时代的硬币。', effects: { luck: 6, intelligence: 4 }, exp: 26, minLevel: 6, weight: 1 },
]
