/**
 * 武侠主题：新增事件。
 */
import type { AdventureEvent } from '../themes.js'

export const WUXIA_NEW_EVENTS: readonly AdventureEvent[] = [
  // ---- 日常（55）----
  { id: 'cockcrow-practice', title: '鸡鸣练拳', description: '天未亮，村口老槐树下已有人在打拳。你路过时他收了势，说看你筋骨不错，晨练贵在坚持。', effects: { strength: 2, vitality: 2 }, exp: 10, weight: 1 },
  { id: 'rice-wine-jar', title: '米酒飘香', description: '巷尾新开了一家酒铺，老板娘舀了一碗刚出坛的米酒请你尝。入口绵甜，后劲却足，她笑着提醒你莫贪杯。', effects: { charisma: 2, vitality: 1 }, exp: 9, weight: 1 },
  { id: 'morning-ferry', title: '渡口晨雾', description: '晨雾锁江，渡船迟迟不开。船夫蹲在船头抽旱烟，说雾里行船最忌心急，江湖人得学会等。', effects: { intelligence: 2, luck: 1 }, exp: 10, weight: 1 },
  { id: 'herb-picking', title: '峭壁采药', description: '药农说崖壁上那株七叶草能治内伤，你攀上去采时脚下一滑，好在抓住藤蔓只擦破了手掌。', effects: { agility: 3, vitality: -1 }, exp: 12, weight: 1 },
  { id: 'sword-polishing', title: '磨剑石前', description: '铁匠铺的磨剑石前，你蹲了一个时辰替老师傅磨剑。他捋着胡子说，剑磨的是性子，不是铁。', effects: { strength: 2, intelligence: 1 }, exp: 10, weight: 1 },
  { id: 'storyteller-tale', title: '说书人', description: '茶馆里说书人正讲到「剑圣雪夜战群雄」，说到关键处一拍醒木：欲知后事，且听下回分解。', effects: { intelligence: 2, charisma: 1 }, exp: 9, weight: 1 },
  { id: 'rain-pavilion', title: '雨亭避雨', description: '骤雨突至，你在凉亭躲雨，遇见一位吹笛的少女。雨停时她已不见，只留笛声在檐角绕了许久。', effects: { charisma: 3, luck: 1 }, exp: 11, weight: 1 },
  { id: 'night-watch', title: '更鼓声声', description: '更夫敲过三更，你随他巡了半条街。他说夜里听得见许多白天听不见的声音，江湖的秘密都藏在暗处。', effects: { vitality: 2, agility: 1 }, exp: 10, weight: 1 },
  { id: 'bridge-challenge', title: '桥头切磋', description: '桥头一位挑担的老汉放下担子，非要与你比划几招。你点到为止，他乐呵呵地说后生可畏。', effects: { strength: 3, charisma: 1 }, exp: 11, weight: 1 },
  { id: 'acupuncture', title: '老郎中施针', description: '老郎中一眼看出你气血不畅，不由分说给你扎了九针。针到之处酸麻难忍，拔针后浑身却轻快了三分。', effects: { vitality: 3, agility: -1 }, exp: 13, weight: 1 },
  { id: 'mantis-fist', title: '螳螂拳师', description: '田埂上一位汉子以螳螂拳捕虫，出手如电。他见你看得入神，便拆了几招给你看，说拳法源于田间。', effects: { agility: 3, strength: 1 }, exp: 11, weight: 1 },
  { id: 'pigeon-letter', title: '飞鸽传书', description: '一只信鸽落在你肩上，脚环上绑着字条却无落款。你替它喂了水，鸽子咕咕叫了两声便飞走了。', effects: { luck: 3, intelligence: 1 }, exp: 11, weight: 1 },
  { id: 'wonton-stall', title: '馄饨摊', description: '深夜馄饨摊热气腾腾，摊主多给你捞了几个。邻座落魄剑客吃得呼噜响，结账时才发现他早被人请了。', effects: { vitality: 2, luck: 2 }, exp: 11, weight: 1 },
  { id: 'broken-bridge', title: '断桥残月', description: '断桥边有人对着残月吹箫，箫声呜咽如诉。你听了半晌，那人回头问：你也睡不着么？', effects: { charisma: 2, intelligence: 1 }, exp: 10, weight: 1 },
  { id: 'beggar-chess', title: '棋丐对弈', description: '城隍庙前的老乞丐摆着残局，输赢都不要钱，只要陪他下一盘。他落子极慢，说棋如人生，急不得。', effects: { intelligence: 3, charisma: 1 }, exp: 11, weight: 1 },
  { id: 'well-water', title: '古井打水', description: '清晨古井边排着打水的队伍，你帮独臂的老伯提了十桶水。他拍拍你的肩，说这井水养人，也养恩。', effects: { strength: 2, charisma: 2 }, exp: 10, weight: 1 },
  { id: 'bamboo-forest', title: '竹林听风', description: '风过竹林沙沙作响，你循声而入，见满地断竹齐整如削——是刀气所致。林深处隐约有人叹息。', effects: { agility: 2, intelligence: 2 }, exp: 11, weight: 1 },
  { id: 'kite-string', title: '纸鸢断线', description: '孩童的纸鸢断了线，落在你家屋顶。你纵身上屋取回，孩子们围着你要学轻功。', effects: { agility: 2, charisma: 1 }, exp: 9, weight: 1 },
  { id: 'mountain-temple', title: '山寺早课', description: '山寺钟声穿透晨雾，你随僧人上了早课。住持说施主有缘，赠你一枚护身符，嘱你行路小心。', effects: { luck: 2, vitality: 1 }, exp: 10, weight: 1 },
  { id: 'hot-spring', title: '野温泉', description: '山坳里一汪野温泉冒着热气，你泡到骨头都酥了才起身，四肢软绵绵的，一时半会儿提不起劲。', effects: { vitality: 4, strength: -1 }, exp: 14, weight: 1 },
  { id: 'tofu-seller', title: '豆腐西施', description: '豆腐摊的姑娘手起刀落，嫩豆腐切得方方正正。她说卖豆腐靠的是稳，武功也一样。', effects: { agility: 2, charisma: 1 }, exp: 9, weight: 1 },
  { id: 'bandit-toll', title: '买路钱', description: '山道上一伙小毛贼拦住去路，为首的抖着刀要买路钱。你看他手抖得厉害，便掏了十几个铜板打发。', effects: { luck: 2, charisma: 1 }, exp: 9, weight: 1 },
  { id: 'forge-bellows', title: '炉边打铁', description: '铁匠铺里炉火正旺，你帮着拉了半天风箱，胳膊酸得抬不起来，却也懂了什么叫百炼成钢。', effects: { strength: 3, vitality: 1 }, exp: 11, weight: 1 },
  { id: 'midnight-cat', title: '夜猫惊魂', description: '夜里一只黑猫从你脚边窜过，你下意识闪身，正好避开身后飞来的暗器。猫蹲在墙头，绿眼睛盯着你。', effects: { agility: 3, luck: -1 }, exp: 14, weight: 1 },
  { id: 'old-boxer', title: '老拳师', description: '巷口打拳的老拳师年过七旬，拳风依旧虎虎生风。他教你一个桩功，说站得住，才打得动。', effects: { strength: 2, vitality: 2 }, exp: 11, weight: 1 },
  { id: 'wine-jar', title: '窖藏老酒', description: '客栈后院埋着一坛三十年的老酒，掌柜挖出来请你品。酒入喉辛辣滚烫，他说这酒等的就是个知味人。', effects: { charisma: 2, luck: 1 }, exp: 10, weight: 1 },
  { id: 'sword-buyer', title: '收剑客', description: '一位白须老者走街串巷收旧剑，开价公道。他掂了掂你的剑，说剑有灵，要多带它见见风。', effects: { intelligence: 2, strength: 1 }, exp: 9, weight: 1 },
  { id: 'tombstone-rites', title: '无名墓', description: '乱葬岗边立着一座无字碑，碑前却供着新酒。守墓人说，江湖人的恩怨，死了也就了了。', effects: { intelligence: 2, luck: 1 }, exp: 10, weight: 1 },
  { id: 'cicada-sound', title: '夏蝉入窗', description: '午后一只蝉飞进窗来，聒噪不停。你赶了几次未果，索性坐下听它叫了一下午，倒听出了几分禅意。', effects: { intelligence: 2, vitality: 1 }, exp: 9, weight: 1 },
  { id: 'fortune-teller', title: '测字摊', description: '测字先生看了你的掌纹直摇头，又看了你的字说峰回路转。他收了卦钱，补了句：事在人为。', effects: { luck: 3, intelligence: 1 }, exp: 11, weight: 1 },
  { id: 'water-mill', title: '磨坊一夜', description: '借宿磨坊，老磨工彻夜赶工。你帮忙添麦子，听他讲当年押镖走南闯北的旧事，说到天亮。', effects: { vitality: 2, charisma: 1 }, exp: 10, weight: 1 },
  { id: 'village-archery', title: '百步穿杨', description: '猎户家墙上挂着自制的弓，你试拉了几下，又照着树上的红绳射了十箭，终于中了一箭。', effects: { agility: 3, strength: 1 }, exp: 11, weight: 1 },
  { id: 'night-hunt', title: '夜猎山猪', description: '山猪拱了村口的菜地，你随猎户进山围猎。山猪横冲直撞，你滚了一身泥才把它撵走。', effects: { strength: 2, vitality: 2 }, exp: 11, weight: 1 },
  { id: 'lantern-fair', title: '灯会猜谜', description: '元宵灯会，你连猜中五盏灯谜，摊主送了你一盏走马灯。灯影里人群熙攘，笑语如潮。', effects: { intelligence: 2, luck: 1 }, exp: 10, weight: 1 },
  { id: 'stray-dog', title: '瘸腿黄狗', description: '一只瘸腿黄狗跟了你三条街，你分了半个烧饼给它。它摇着尾巴，在你脚边趴了一夜。', effects: { charisma: 2, luck: 1 }, exp: 9, weight: 1 },
  { id: 'beggar-drill', title: '丐帮晨练', description: '城隍庙前几十个乞丐排成两行，齐刷刷地练着打狗棒法。领头的乞丐回头冲你咧嘴一笑，露出颗金牙。', effects: { agility: 2, charisma: 1 }, exp: 10, weight: 1 },
  { id: 'pawnshop', title: '当铺奇闻', description: '当铺柜台后的小伙计按规矩压价，你把祖传的玉佩当了，换来的银两只够买一壶酒。出门时你回头，看见他偷偷擦了擦玉佩。', effects: { luck: 2, charisma: -2 }, exp: 13, weight: 1 },
  { id: 'night-boat', title: '夜航船', description: '夜航船上人声嘈杂，你靠窗听一位赶考书生讲鬼故事。讲到兴起，船头忽然传来一声锣响。', effects: { intelligence: 2, charisma: 1 }, exp: 10, weight: 1 },
  { id: 'cliff-plank-road', title: '栈道惊魂', description: '悬崖栈道的木板年久失修，你踩断一块，单手挂在铁链上荡了半盏茶才翻上来，后背全是冷汗。', effects: { agility: 3, vitality: 1 }, exp: 14, weight: 1 },
  { id: 'old-ox', title: '老牛救主', description: '耕地的老牛忽然发狂冲向孩童，你抢上前一把抱开。老牛随即安静下来，农人说是牛受了惊。', effects: { strength: 2, charisma: 2 }, exp: 11, weight: 1 },
  { id: 'eaves-rain', title: '檐下听雨', description: '你坐在檐下听了一夜雨，看雨滴在青石板上砸出小坑。天光放亮时，忽然想通了一招剑法的变化。', effects: { intelligence: 3, agility: 1 }, exp: 13, weight: 1 },
  { id: 'apprentice-recruit', title: '收徒风波', description: '镖局的趟子手领来一个瘦弱少年，说这孩子想拜你为师。少年跪在地上，眼神却倔强得像头小狼。', effects: { charisma: 3, intelligence: 1 }, exp: 12, weight: 1 },
  { id: 'acrobat-troupe', title: '杂耍班子', description: '街头杂耍班子翻跟头、走钢丝、胸口碎大石，看得人喝彩连连。班主收钱时，多看了你一眼。', effects: { agility: 2, luck: 1 }, exp: 9, weight: 1 },
  { id: 'salt-cart', title: '盐道苦力', description: '盐道上的苦力们推着盐车哼着号子，你帮着推了一段陡坡。领头的汉子说，这世上最硬的不是刀，是肩膀。', effects: { strength: 3, vitality: 1 }, exp: 11, weight: 1 },
  { id: 'river-fishing', title: '寒江独钓', description: '江边一位蓑衣老翁独钓寒江，半天没动静。你说这江里怕没鱼，他笑答：钓的不是鱼。', effects: { intelligence: 2, luck: 1 }, exp: 10, weight: 1 },
  { id: 'inn-mouse', title: '客栈闹鼠', description: '客栈夜里闹鼠，你循声追了半宿，在柴房墙角堵住一只肥鼠。掌柜赔笑道谢，免了你半日房钱。', effects: { agility: 2, luck: 1 }, exp: 10, weight: 1 },
  { id: 'moon-gazing', title: '望月台', description: '中秋夜你登上城头望月，见远处屋顶上有个白衣人影也在赏月。月亮圆了又缺，那人却始终没动。', effects: { luck: 2, charisma: 1 }, exp: 10, weight: 1 },
  { id: 'plum-stakes', title: '梅花桩', description: '武馆后院的梅花桩上落满雪，你踩着桩走了一圈，又掉下来三回。馆主在窗后看了，没说话。', effects: { agility: 3, vitality: 1 }, exp: 13, weight: 1 },
  { id: 'knife-sharpening', title: '磨刀老头', description: '巷尾磨刀老头走街串巷，吆喝声拖着长调。他替你磨了把菜刀，刀口亮得能照见人影。', effects: { strength: 1, luck: 2 }, exp: 9, weight: 1 },
  { id: 'night-porridge', title: '深夜粥铺', description: '城门口深夜支着一口大锅，粥铺老板给赶路人免费添粥。他说年轻时也受过人一碗粥的恩。', effects: { vitality: 2, charisma: 2 }, exp: 10, weight: 1 },
  { id: 'calligraphy', title: '题字', description: '酒楼上有人请你题字，你提笔写下「快意恩仇」四字。满座叫好，说这字有剑气。', effects: { charisma: 3, intelligence: 1 }, exp: 11, weight: 1 },
  { id: 'wasp-nest', title: '马蜂窝', description: '顽童捅了马蜂窝，蜂群炸开。你脱下外袍护住孩子，自己被蜇了好几下，肿着半边脸去讨药。', effects: { charisma: 2, vitality: 1 }, exp: 10, weight: 1 },
  { id: 'goose-shadow', title: '雁过留声', description: '一行大雁掠过天际，排成「人」字。你望着雁阵出神，忽然想起远方故人，胸口一暖。', effects: { charisma: 1, luck: 2 }, exp: 9, weight: 1 },
  { id: 'stone-lion', title: '石狮下的信', description: '衙门前的石狮子嘴里衔着一封信，你取下一看，是张泛黄的婚书，落款处的字迹已模糊。', effects: { intelligence: 2, luck: 1 }, exp: 10, weight: 1 },
  { id: 'frost-morning', title: '霜晨赶路', description: '霜晨赶路，马蹄踏碎薄冰。你在道旁茶棚歇脚，茶博士说今年入冬早，江湖人该添件厚衣裳了。', effects: { vitality: 2, agility: 1 }, exp: 10, weight: 1 },
  // ---- 冒险（27）----
  { id: 'escort-robbery', title: '劫镖', description: '镖车行至黑风岭，一声唿哨，山道两侧跳出七八条黑影。镖头沉声道：护镖，还是保命，你选。', effects: { strength: 3, agility: 2 }, exp: 15, minLevel: 2, weight: 1 },
  { id: 'bandit-inn', title: '黑店', description: '这家客栈的招牌菜是肉包子，可后厨的磨刀声比剁馅声还勤。你捏着筷子，瞥见掌柜眼里闪过一丝凶光。', effects: { agility: 3, intelligence: 2 }, exp: 14, minLevel: 2, weight: 1 },
  { id: 'snake-valley', title: '蛇谷', description: '蛇谷的雾气里游走着数不清的毒蛇，谷口插着「擅入者死」的木牌。你握紧火把，听见蛇信子嘶嘶作响。', effects: { vitality: 3, agility: 2 }, exp: 16, minLevel: 2, weight: 1 },
  { id: 'dungeon-rescue', title: '地牢救人', description: '地牢里关着一位被拷打多日的侠士，铁链锁着他的琵琶骨。看守巡逻的间隙只有一炷香，够不够，就看你的了。', effects: { strength: 3, intelligence: 2 }, exp: 16, minLevel: 2, weight: 1 },
  { id: 'stolen-manual', title: '夺回秘籍', description: '藏经阁的秘籍被盗，线索指向城南的销金窟。你混进赌坊，看见那本秘籍正被人当作赌注摆在桌上。', effects: { agility: 3, luck: 2 }, exp: 15, minLevel: 2, weight: 1 },
  { id: 'masked-guide', title: '蒙面指路', description: '深夜一个蒙面人拦住你，说前方十里有人设伏等你。他丢下一张路线图，转身消失在屋脊之后。', effects: { intelligence: 3, luck: 2 }, exp: 14, minLevel: 2, weight: 1 },
  { id: 'broken-temple-brawl', title: '破庙混战', description: '破庙里两拨仇家狭路相逢，一言不合便动起手来。你被夹在中间，躲也不是，打也不是。', effects: { agility: 3, strength: 2 }, exp: 14, minLevel: 2, weight: 1 },
  { id: 'river-bandits', title: '水匪截船', description: '渡船行至江心，几条快船围了上来，船上的水匪亮出钩镰枪。船老大喊：会水的跳水，不会水的听天由命。', effects: { agility: 3, vitality: 2 }, exp: 15, minLevel: 2, weight: 1 },
  { id: 'beauty-plea', title: '红颜求助', description: '一位蒙纱女子拦住你的马，说胞弟被恶霸掳去抵债。她递来一支金钗：若先生肯援手，此物为谢。', effects: { charisma: 3, luck: 2 }, exp: 14, minLevel: 2, weight: 1 },
  { id: 'drunk-sword', title: '醉酒狂刀', description: '酒馆里一个醉汉耍起狂刀，刀锋擦着你的鼻尖掠过。他忽然停手，红着眼问：你说，我这一刀够不够快？', effects: { agility: 4, charisma: 1 }, exp: 15, minLevel: 2, weight: 1 },
  { id: 'zither-boat', title: '江上琴声', description: '夜泊江畔，一艘画舫上传来琴声，曲调暗合一套剑法的起手式。你凝神听了一夜，琴声却在破晓前戛然而止。', effects: { intelligence: 3, agility: 2 }, exp: 16, minLevel: 2, weight: 1 },
  { id: 'marriage-arena', title: '比武招亲', description: '城门口搭起擂台比武招亲，台上的姑娘却把绣球抛向了你。台下哄堂大笑，她似笑非笑地看着你。', effects: { strength: 3, charisma: 2 }, exp: 14, minLevel: 2, weight: 1 },
  { id: 'night-palace', title: '夜探王府', description: '王府后院灯火通明，据说今晚有一场见不得人的交易。你翻过三道院墙，落脚的瓦片忽然「咔」地一响。', effects: { agility: 4, intelligence: 2 }, exp: 16, minLevel: 2, weight: 1 },
  { id: 'snow-wolf', title: '雪夜狼群', description: '雪夜的山道上，十几双绿油油的眼睛围了上来。狼群低伏着身子，喉咙里滚着低沉的呜咽。', effects: { strength: 3, vitality: 3 }, exp: 15, minLevel: 2, weight: 1 },
  { id: 'iron-palm', title: '铁掌试功', description: '铁掌帮的弟子拦住你，说要借你的背试试新练的掌力。你扎稳马步硬接了七掌，胸口一阵发闷。', effects: { vitality: 4, strength: 2 }, exp: 17, minLevel: 3, weight: 1 },
  { id: 'cliff-leap', title: '悬崖轻功', description: '悬崖上垂下一道铁索，下头是万丈深渊。据说轻功练到火候的人，能踩着崖壁借力而上。你深吸一口气。', effects: { agility: 4, vitality: 2 }, exp: 17, minLevel: 3, weight: 1 },
  { id: 'arena-duel', title: '擂台争锋', description: '擂台上的连胜者点名叫你上台，说赢了便送你一套拳谱。满场目光齐刷刷落过来，退无可退。', effects: { strength: 4, charisma: 2 }, exp: 17, minLevel: 3, weight: 1 },
  { id: 'night-assassin', title: '夜半刺客', description: '你吹熄油灯准备就寝，窗棂外传来极轻的脚步声。江湖经验告诉你：来者不善，善者不来。', effects: { agility: 4, luck: 2 }, exp: 17, minLevel: 3, weight: 1 },
  { id: 'water-sprint', title: '水上漂', description: '芦苇荡前，一位老者说，只要你能踏着浮萍走到对岸，就把「水上漂」的诀窍传给你。', effects: { agility: 4, intelligence: 1 }, exp: 16, minLevel: 3, weight: 1 },
  { id: 'seven-injuries', title: '七伤拳谱', description: '地摊上摆着一卷破旧的七伤拳谱，卖主说练此拳者先伤己后伤人。你翻开两页，纸上的批注笔迹殷红。', effects: { strength: 4, vitality: -2 }, exp: 17, minLevel: 3, weight: 1 },
  { id: 'flower-thief', title: '追踪采花贼', description: '官府悬赏捉拿采花贼，线索指向花街柳巷。你扮成寻欢客混进去，却发现自己也被人盯上了。', effects: { intelligence: 4, agility: 2 }, exp: 17, minLevel: 3, weight: 1 },
  { id: 'hostage', title: '救人质', description: '悍匪劫了镖局的少东家索要赎金，你受镖头之托夜入匪巢。火把映着墙上的影子，每一步都踩在刀尖上。', effects: { agility: 3, intelligence: 3 }, exp: 18, minLevel: 3, weight: 1 },
  { id: 'tomb-trap', title: '机关古墓', description: '古墓的石门后机关重重，脚下的石板一踩便往下陷。墙上的壁画记载着墓主生平，也藏着唯一的生路。', effects: { intelligence: 4, luck: 2 }, exp: 18, minLevel: 3, weight: 1 },
  { id: 'hermit-trial', title: '隐士试剑', description: '竹林深处的隐士说你的剑路太杂，要与你过三招。他随手折了根竹枝，你竟一招都没接住。', effects: { agility: 3, intelligence: 3 }, exp: 18, minLevel: 3, weight: 1 },
  { id: 'flag-capture', title: '夺旗大会', description: '山贼们摆下夺旗大会，胜者可得一箱金银。旗杆高悬在峭壁之上，守旗的汉子手里提着两把板斧。', effects: { strength: 4, agility: 2 }, exp: 17, minLevel: 3, weight: 1 },
  { id: 'acupoint-seal', title: '失传点穴', description: '游方郎中露了一手点穴功夫，说这是失传的「闭气八穴」。他教你认穴，叮嘱：点人穴道，也要点自己的心性。', effects: { intelligence: 3, agility: 3 }, exp: 17, minLevel: 3, weight: 1 },
  { id: 'sutra-library', title: '藏经阁', description: '深夜的藏经阁里，你借着月光翻找一部失传的内功心法。忽然听见书架后传来翻书的沙沙声。', effects: { intelligence: 4, luck: 1 }, exp: 18, minLevel: 3, weight: 1 },
  // ---- 史诗（7）----
  { id: 'dragon-blade', title: '屠龙刀', description: '传闻屠龙刀重现江湖，群雄蜂拥而至。刀在谁手，谁就是众矢之的。你远远看着那柄刀，刀身映着血色残阳。', effects: { strength: 5, luck: 2 }, exp: 21, minLevel: 4, weight: 1 },
  { id: 'league-ambush', title: '盟主之位', description: '武林大会落幕，盟主却遭人暗算重伤。众人目光落在你身上，有人低声问：这盟主之位，你接是不接？', effects: { charisma: 5, strength: 2 }, exp: 22, minLevel: 4, weight: 1 },
  { id: 'sutra-crisis', title: '少林之变', description: '少林寺一夜之间封山，据说是藏经阁的七十二绝技被人盗走。你赶到山门时，两位护法僧拦在面前。', effects: { intelligence: 4, luck: 3 }, exp: 20, minLevel: 4, weight: 1 },
  { id: 'demon-cult', title: '魔教总坛', description: '魔教总坛设于绝壁之上，机关重重，明哨暗桩层层叠叠。你受人所托潜入其中，却总觉得处处有人引路。', effects: { agility: 5, intelligence: 3 }, exp: 23, minLevel: 5, weight: 1 },
  { id: 'sword-grave', title: '万剑冢', description: '剑冢之中插着历代高手的佩剑，剑鸣声此起彼伏。守剑人说：取一柄剑，便要承一段因果。', effects: { strength: 4, agility: 4 }, exp: 22, minLevel: 5, weight: 1 },
  { id: 'heaven-gate', title: '天门开', description: '江湖传言，月圆之夜天门将开，得入者可得长生诀。九大门派齐聚天门山，各怀心思。', effects: { luck: 5, intelligence: 3 }, exp: 24, minLevel: 5, weight: 1 },
  { id: 'summit-duel', title: '紫禁之巅', description: '天下第一的剑客与刀客约战于紫禁之巅，观战者云集。这一战的胜负，将改写整个武林的格局。', effects: { agility: 6, strength: 4 }, exp: 26, minLevel: 6, weight: 1 },
]
