/**
 * 玄幻主题：新增事件。
 */
import type { AdventureEvent } from '../themes.js'

export const XIANXIA_NEW_EVENTS: readonly AdventureEvent[] = [
  // ===== 日常（55 个，无 minLevel）=====
  { id: 'morning-qi', title: '晨练吐纳', description: '每日清晨你都在山巅吐纳，今日恰逢紫气东来，一缕暖流顺着经脉沉入丹田，整日的疲惫一扫而空。', effects: { vitality: 2 }, exp: 10, weight: 1 },
  { id: 'market-fruit', title: '灵果善缘', description: '集市上卖灵果的老翁称重时手一抖，多给了你一颗百年朱果。他摆摆手说：「多出来的那颗，算结个善缘。」', effects: { luck: 2, charisma: 1 }, exp: 10, weight: 1 },
  { id: 'ragged-manual', title: '残卷批注', description: '你在旧书摊淘到一本缺了封面的功法残卷，页脚批注竟是某位元婴老祖年轻时的手笔，寥寥数语抵得上数年苦修。', effects: { intelligence: 3 }, exp: 12, weight: 1 },
  { id: 'lost-herb', title: '迷谷采药', description: '为采崖壁上那株还魂草，你在山谷里绕到日头偏西，才发现脚下的路被阵法改过——有人不想让人靠近那座荒坟。', effects: { agility: 2, intelligence: 1 }, exp: 11, weight: 1 },
  { id: 'talisman-bargain', title: '符箓有缘', description: '符箓摊的老板娘说你面相与她的符有缘，半价卖你一张辟尘符。你贴身收好，果然连着三天没沾半点尘土。', effects: { luck: 1, agility: 1 }, exp: 9, weight: 1 },
  { id: 'old-sword', title: '破旧佩剑', description: '当铺角落躺着一把锈迹斑斑的旧剑，老板说它搁了三十年无人问津。你随手一拂，剑身竟发出一声极轻的龙吟。', effects: { strength: 2, luck: 1 }, exp: 11, weight: 1 },
  { id: 'tea-house', title: '茶楼听书', description: '茶楼说书人正讲一位剑仙的往事，讲到关键处却卖起关子。你替他把后半段续上，满堂修士抚掌大笑，他悄悄塞给你一壶灵茶。', effects: { charisma: 3 }, exp: 12, weight: 1 },
  { id: 'stream-box', title: '溪边拾匣', description: '你在溪边洗濯道袍，上游漂来一只半沉半浮的木匣。匣中是一枚温润的暖玉，还带着淡淡的药香。', effects: { luck: 3 }, exp: 10, weight: 1 },
  { id: 'alchemy-boom', title: '炼丹炸炉', description: '你头一回开炉炼丹，火候没控住，「轰」的一声丹炉炸了。你满脸炉灰，却意外炼成了一粒歪歪扭扭的辟谷丹。', effects: { intelligence: 2, vitality: 1 }, exp: 12, weight: 1 },
  { id: 'night-watch', title: '守夜遇猪', description: '今夜轮到你守山门，月上中天时，一头偷灵米的野猪妖撞上了你。你与它大眼瞪小眼，最后分它半袋灵米，它甩着尾巴跑了。', effects: { charisma: 2, agility: 1 }, exp: 10, weight: 1 },
  { id: 'bamboo-rain', title: '竹林听雨', description: '你在后山竹林的雨声里打坐，忽然听见竹节里传来「咚咚」的轻响——那是竹灵在学你吐纳的节奏。', effects: { vitality: 2, intelligence: 1 }, exp: 11, weight: 1 },
  { id: 'mirror-pond', title: '镜湖倒影', description: '镜湖的水面像一面天然的镜子，你照见自己的倒影时，水中的「你」竟冲你眨了眨眼。你揉揉眼睛，它又恢复如常。', effects: { intelligence: 2, luck: 1 }, exp: 11, weight: 1 },
  { id: 'millstone-day', title: '石磨半日', description: '你帮山下农户推了一下午的石磨，老黄牛一直拿尾巴替你赶蚊子。农户过意不去，硬塞给你一筐新摘的灵薯。', effects: { strength: 2, charisma: 1 }, exp: 10, weight: 1 },
  { id: 'cat-blessing', title: '灵猫讨食', description: '一只三花灵猫蹲在你洞府门口不走，你分它半条烤鱼。它舔了舔爪子，在你额头轻轻一按，你顿时觉得精神一振。', effects: { luck: 2, charisma: 1 }, exp: 10, weight: 1 },
  { id: 'sutra-copy', title: '抄经悟法', description: '你被罚抄《静心经》一百遍，抄到第七十三遍时，忽然读懂了字里行间藏着的呼吸法门。', effects: { intelligence: 3, vitality: 1 }, exp: 13, weight: 1 },
  { id: 'ferry-stone', title: '渡船河石', description: '渡口的老艄公撑船时哼着不成调的歌，说那是河神教的。你听得入神，下船时他递给你一枚青色的河卵石。', effects: { luck: 2, vitality: 1 }, exp: 10, weight: 1 },
  { id: 'wind-bell', title: '檐下风铃', description: '道观檐下的风铃无风自响，三长两短。老道说那是山神在报平安，还说今天山里的野兽会格外温顺。', effects: { luck: 2 }, exp: 9, weight: 1 },
  { id: 'kite-letter', title: '纸鸢传信', description: '你在山崖上放纸鸢，一只灵鹤衔走了你的线。它绕山三圈，竟带回一封写给「有缘人」的残信，信上只剩一行褪色的字。', effects: { intelligence: 2, agility: 1 }, exp: 11, weight: 1 },
  { id: 'tofu-girl', title: '豆腐西施', description: '山脚镇上的豆腐铺子新来了个手脚麻利的姑娘，她见你修行辛苦，往豆浆里多舀了一勺糖，说是「修行人的甜头」。', effects: { charisma: 2, vitality: 1 }, exp: 10, weight: 1 },
  { id: 'stone-step', title: '青石阶异', description: '你每日上山的那条青石阶，今日忽然少了一级。你在原处立了一会儿，竟隐约听见地底传来「啵」的一声。', effects: { intelligence: 2, luck: 1 }, exp: 11, weight: 1 },
  { id: 'pot-hole', title: '瓦罐漏底', description: '你炖的灵药汤把瓦罐底烧穿了一个洞，汤漏进土里。第二天，那处泥土里长出一株碧油油的药苗。', effects: { luck: 3 }, exp: 10, weight: 1 },
  { id: 'frost-sword', title: '霜晨剑意', description: '初冬的清晨，你随手折下一根结满霜花的枯枝当剑使，竟悟出一式带着霜意的剑招。', effects: { agility: 2, strength: 1 }, exp: 11, weight: 1 },
  { id: 'spirit-magpie', title: '灵鹊衔石', description: '一只灵鹊把巢筑在了你窗外的桃树上，日日衔来亮晶晶的小石子。你数了数，正好九颗。', effects: { luck: 2 }, exp: 9, weight: 1 },
  { id: 'chess-ape', title: '对弈老猿', description: '山里的老猿会下棋，你与它对弈三局输了三局。它挠挠头，丢给你一颗珍藏的松果，那松果带着千年松脂的香气。', effects: { intelligence: 3, charisma: 1 }, exp: 12, weight: 1 },
  { id: 'sugar-painting', title: '夜市糖画', description: '夜市里有个画糖画的老匠人，他画了一条小蛟龙递给你，说：「这龙有灵性，含化它，能压一压心火。」', effects: { vitality: 2, charisma: 1 }, exp: 10, weight: 1 },
  { id: 'well-moon', title: '井中月碎', description: '你在古井边打水，井底的月亮忽然碎了，化作满井的银光。你再打一桶水，桶里竟浮着半枚发光的贝壳。', effects: { luck: 3 }, exp: 11, weight: 1 },
  { id: 'broom-slab', title: '扫地见碑', description: '你替师父扫了三天的落叶，扫到第三天，发现落叶总在同一个位置打转——那底下埋着一块刻着「静」字的石板。', effects: { intelligence: 2, luck: 1 }, exp: 12, weight: 1 },
  { id: 'lamp-oil', title: '续灯油', description: '祖师堂的灯油快尽了，你连夜下山买油。回来时天边泛起鱼肚白，油灯的火苗跳了跳，像在跟你道谢。', effects: { charisma: 2, vitality: 1 }, exp: 10, weight: 1 },
  { id: 'wooden-sword', title: '木剑生芒', description: '你拿木剑练了八百遍基础剑式，最后一式劈下时，木剑的剑尖竟冒出一寸青芒。', effects: { strength: 2, agility: 1 }, exp: 12, weight: 1 },
  { id: 'cold-spring', title: '冷泉沐足', description: '你在后山冷泉边沐足，泉底的青苔忽然泛起微光，水流顺着脚踝盘旋，带走了一夜的疲惫。', effects: { vitality: 3 }, exp: 10, weight: 1 },
  { id: 'incense-smoke', title: '香火绕身', description: '你在城隍庙躲雨，供桌上的香火烟气竟凝成一条细线，绕着你转了三圈才散。庙祝说，这是「贵人相」。', effects: { luck: 2, charisma: 1 }, exp: 10, weight: 1 },
  { id: 'koi-jump', title: '锦鲤跃手', description: '观里的锦鲤池今日异常热闹，一尾金鳞锦鲤在你经过时跃出水面，正好落进你手里，又「啪」地蹦了回去。', effects: { luck: 2 }, exp: 9, weight: 1 },
  { id: 'morning-bell', title: '晨钟七响', description: '你值了一夜的更，敲响晨钟时，钟声在山谷里荡了七圈才散。长老说，今天山里的灵气格外顺。', effects: { vitality: 2, charisma: 1 }, exp: 10, weight: 1 },
  { id: 'herb-drying', title: '晒药清香', description: '你帮药圃的师兄晒药，满院子都是灵药的清香。你打了个喷嚏，吸进一缕药气，鼻尖一热，竟觉得目力清明了几分。', effects: { intelligence: 1, vitality: 2 }, exp: 10, weight: 1 },
  { id: 'stove-rice', title: '灶火添米', description: '你在伙房帮工，灶膛里的火忽然自己旺了三分，饭甑里的灵米蒸得粒粒开花。炊事长老往你碗里多扣了一勺。', effects: { vitality: 2, charisma: 1 }, exp: 10, weight: 1 },
  { id: 'frog-chant', title: '蛙鸣入定', description: '夏夜的蛙鸣吵得你无法入定，你索性放开灵识去听，竟从杂乱的声音里听出一段天然的音律。', effects: { intelligence: 2, luck: 1 }, exp: 11, weight: 1 },
  { id: 'snow-tracks', title: '雪中脚印', description: '大雪封山，你踩出一行脚印去挑水，回来时发现脚印旁多了一行更小的脚印，像是某种小兽跟着你走了一路。', effects: { agility: 2, luck: 1 }, exp: 10, weight: 1 },
  { id: 'paper-crane', title: '纸鹤传讯', description: '你用旧符纸折了一只纸鹤，随手一吹，纸鹤竟扑棱棱飞了起来，绕屋三圈后落在你肩头，翅膀上浮出一行小字。', effects: { intelligence: 3 }, exp: 12, weight: 1 },
  { id: 'ox-whip', title: '牛鞭暗合', description: '你替农人赶了一下午的牛，牛鞭甩得虎虎生风。收工时你才发觉，这甩鞭的诀窍竟暗合一门鞭法。', effects: { agility: 2, strength: 1 }, exp: 11, weight: 1 },
  { id: 'lantern-riddle', title: '灯会猜谜', description: '元宵灯会上，一盏写着古怪谜语的灯笼忽然飘到你面前。你答出谜底，灯笼里掉出一颗糖丸。', effects: { intelligence: 2, luck: 1 }, exp: 11, weight: 1 },
  { id: 'jade-spring', title: '玉泉煮茶', description: '你取玉泉的水煮茶，茶叶在壶里舒展成一朵莲花的样子。茶汤入口，唇齿间竟留着一丝灵力回甘。', effects: { vitality: 2, charisma: 1 }, exp: 10, weight: 1 },
  { id: 'mosquito-bite', title: '山蚊叮咬', description: '你在林中打坐，被一只巴掌大的山蚊叮了一口，又痛又痒。可三日后，被叮处竟凝出一颗米粒大的灵砂。', effects: { vitality: 2, luck: 1 }, exp: 12, weight: 1 },
  { id: 'tile-repair', title: '补瓦得钱', description: '暴雨冲垮了山门的一角瓦檐，你踩着梯子爬上补瓦，从瓦缝里摸出一枚被雨水泡得发亮的铜钱。', effects: { strength: 1, luck: 2 }, exp: 10, weight: 1 },
  { id: 'chrysanthemum-wine', title: '菊花酿', description: '你跟着酿酒的老修士学酿菊花酒，他往酒坛里滴了三滴自己的心血，说这样酿出来的酒能「通窍」。', effects: { intelligence: 2, charisma: 1 }, exp: 11, weight: 1 },
  { id: 'cicada-shell', title: '蝉蜕入药', description: '你在老槐树下捡到一枚晶莹的蝉蜕，蝉蜕里竟残留着一丝化形妖气。老药师说，这是百年蝉妖蜕下的壳，入药可固本培元。', effects: { vitality: 3 }, exp: 12, weight: 1 },
  { id: 'log-bridge', title: '独木桥过', description: '山涧的独木桥被洪水冲走了半截，你背着一筐药材跳了过去。对岸，一个樵夫看得目瞪口呆，硬要拜你为师。', effects: { agility: 2, charisma: 1 }, exp: 11, weight: 1 },
  { id: 'ink-grind', title: '研墨有灵', description: '你帮师兄研了半夜的墨，砚台里的墨汁泛起一层银光。师兄说这砚是祖传的，研墨的人心静，墨里就有灵。', effects: { intelligence: 2, vitality: 1 }, exp: 10, weight: 1 },
  { id: 'firefly-map', title: '萤火成图', description: '你把满山的萤火虫装进琉璃瓶，挂在床头当灯。半夜里，萤火虫的光芒汇成一张模糊的地图。', effects: { intelligence: 2, luck: 1 }, exp: 11, weight: 1 },
  { id: 'donkey-stops', title: '毛驴止步', description: '你帮镇上的药材铺驮货上山，毛驴走到半路忽然跪下，不肯再走。你顺着它的目光看去，崖缝里长着一株会发光的草。', effects: { luck: 3 }, exp: 11, weight: 1 },
  { id: 'kettle-whistle', title: '茶壶自鸣', description: '你的旧茶壶今天烧水时一直「呜呜」作响，水开后壶嘴竟吐出一缕白烟，凝成一个小小的「吉」字。', effects: { luck: 2 }, exp: 9, weight: 1 },
  { id: 'greedy-cultivation', title: '贪功冒进', description: '你同时修炼两门相冲的功法，贪多求快，灵力在经脉里打起架来，丹田隐隐作痛，修为却实打实涨了一截。', effects: { strength: 3, vitality: -2 }, exp: 14, weight: 1 },
  { id: 'bad-guide', title: '遇人不淑', description: '一位自称「矿脉通」的散修拍着胸脯带你去寻无主灵矿，结果挖开的是妖兽巢穴。你跑得上气不接下气，还被挠了一爪。', effects: { agility: 2, vitality: -1 }, exp: 12, weight: 1 },
  { id: 'lost-loan', title: '灵石难追', description: '你把攒了半年的灵石借给一位同门，他第二日便卷铺盖下山，再没了音讯。你心疼之余，只好把苦水咽进肚里。', effects: { luck: -2, intelligence: 1 }, exp: 10, weight: 1 },
  { id: 'cursed-jade', title: '噬灵玉佩', description: '你在夜市淘到一枚「上古玉佩」，戴了三日才发现它日日偷吸你的灵力。你气得摘下来砸了，碎玉里却滚出一粒丹药。', effects: { vitality: -1, luck: 1 }, exp: 12, weight: 1 },
  { id: 'bitter-pill', title: '苦命丹', description: '一位老妪拦住你，硬塞给你一枚黑乎乎的苦命丹，说吃了能「以苦换甜」。你尝了一口，苦得三天没尝出味道。', effects: { vitality: -1, luck: 1 }, exp: 10, weight: 1 },
  // ===== 冒险（27 个，minLevel 2/3 约各半）=====
  { id: 'beast-hunt', title: '妖兽围猎', description: '宗门发布悬赏，一头独眼狼妖连日祸害山下村落。你随猎队入林，狼妖的咆哮震得松涛如浪。', effects: { strength: 3, agility: 2 }, exp: 15, minLevel: 2, weight: 1 },
  { id: 'ancient-cave', title: '古修洞府', description: '山洪冲开一座古修洞府，门前的禁制已摇摇欲坠。洞府深处，有什么东西正等着第一位来客。', effects: { intelligence: 4, luck: 2 }, exp: 16, minLevel: 2, weight: 1 },
  { id: 'alchemy-match', title: '丹道比试', description: '山下药坊摆下丹道擂台，头名可得一枚筑基丹。你与几位同门轮番开炉，满室药香。', effects: { intelligence: 4, charisma: 1 }, exp: 16, minLevel: 2, weight: 1 },
  { id: 'sect-duel', title: '山门切磋', description: '一位外门师兄当众向你下战书，说赢了他便把剑谱借你。围观的弟子越聚越多。', effects: { strength: 3, agility: 3 }, exp: 15, minLevel: 2, weight: 1 },
  { id: 'ghost-fair', title: '鬼市奇遇', description: '子时的荒郊忽然亮起一盏盏绿灯笼——那是只在阴雨天现身的鬼市。摊位上摆着阳间见不到的物什。', effects: { luck: 4, intelligence: 1 }, exp: 16, minLevel: 2, weight: 1 },
  { id: 'spirit-rain', title: '灵雨润泽', description: '一场带着灵气的雨落在山门，雨水所及之处草木疯长。长老说这是百年一遇的灵雨，赶紧打坐吸收。', effects: { vitality: 4, luck: 2 }, exp: 15, minLevel: 2, weight: 1 },
  { id: 'tame-leopard', title: '驯服灵豹', description: '你在后山遇见一头受伤的幼年灵豹，它戒备地盯着你，爪子在地上刨出深痕。', effects: { charisma: 4, agility: 1 }, exp: 15, minLevel: 2, weight: 1 },
  { id: 'river-peril', title: '渡江遇险', description: '你乘船渡江，江心忽然掀起黑浪，船底传来「笃笃」的叩击声——水下的东西在跟船打招呼。', effects: { agility: 3, strength: 2 }, exp: 15, minLevel: 2, weight: 1 },
  { id: 'nameless-tablet', title: '无名碑文', description: '荒野里立着一块无字的石碑，你用灵识探去，碑中竟传来一整段残缺的功法口诀。', effects: { intelligence: 4, vitality: 1 }, exp: 16, minLevel: 2, weight: 1 },
  { id: 'pill-refining', title: '开炉炼丹', description: '你按古方炼制聚气丹，丹炉里的火光映得满脸通红。最后一刻的收火，成败只在一念之间。', effects: { intelligence: 3, luck: 2 }, exp: 15, minLevel: 2, weight: 1 },
  { id: 'night-raid', title: '夜袭山贼', description: '一伙修士山贼趁夜摸上山门粮库，你巡夜撞个正着。黑暗中，刀光与符火交相辉映。', effects: { strength: 3, agility: 2 }, exp: 15, minLevel: 2, weight: 1 },
  { id: 'bamboo-raft', title: '竹筏漂流', description: '你扎了条竹筏顺流而下，想抄近路去坊市。谁知水底有条成了精的大鱼一路跟着，还时不时顶一下筏尾。', effects: { agility: 3, luck: 2 }, exp: 14, minLevel: 2, weight: 1 },
  { id: 'herb-race', title: '采药竞赛', description: '宗门举办采药竞赛，比谁采的灵药年份更足。你刚进山，就看见一株紫芝长在悬崖边。', effects: { agility: 3, intelligence: 2 }, exp: 15, minLevel: 2, weight: 1 },
  { id: 'message-crane', title: '传讯灵鹤', description: '你受托为一位闭关的师叔送去急信，途中要穿过妖雾弥漫的竹林。灵鹤在你头顶盘旋，催促你加快脚步。', effects: { agility: 3, vitality: 2 }, exp: 14, minLevel: 2, weight: 1 },
  { id: 'foundation-chance', title: '筑基机缘', description: '你修为到了瓶颈，师父说筑基讲究「水到渠成」。恰好山下的地火灵泉近日喷涌，是百年难逢的筑基机缘。', effects: { vitality: 5, luck: 2 }, exp: 18, minLevel: 3, weight: 1 },
  { id: 'demon-cave', title: '妖窟探秘', description: '你循着失踪同门留下的记号，摸进一座妖气冲天的洞窟。洞窟深处，兽吼声一浪高过一浪。', effects: { strength: 4, agility: 3 }, exp: 17, minLevel: 3, weight: 1 },
  { id: 'ghost-officer', title: '鬼差索命', description: '一位青面鬼差拦在你面前，说你阳寿簿上有个名字被涂改过。他盯着你看了半天，忽然转身走了。', effects: { luck: 3, intelligence: 3 }, exp: 16, minLevel: 3, weight: 1 },
  { id: 'tribulation-guard', title: '护法渡劫', description: '你的好友即将渡金丹小劫，邀你替他护法。天雷落下时，他打坐的身影在电光里显得格外单薄。', effects: { vitality: 4, charisma: 2 }, exp: 17, minLevel: 3, weight: 1 },
  { id: 'sword-spirit-owner', title: '剑灵认主', description: '你在藏剑阁擦拭一柄古剑，剑身忽然自行出鞘，绕你三圈，嗡鸣不止——它在挑选主人。', effects: { agility: 4, strength: 2 }, exp: 17, minLevel: 3, weight: 1 },
  { id: 'vein-cave', title: '灵脉洞穴', description: '你发现一处隐秘洞穴，洞中灵气浓郁得凝成白雾。但洞壁上刻着一行血字：擅入者，留一缕神魂。', effects: { intelligence: 4, vitality: 2 }, exp: 17, minLevel: 3, weight: 1 },
  { id: 'beast-wave', title: '兽潮将至', description: '巡逻的斥候回报，深山里兽群躁动，恐有兽潮。你被编入防线，站在青石城头望向黑压压的林海。', effects: { strength: 4, vitality: 3 }, exp: 17, minLevel: 3, weight: 1 },
  { id: 'bone-reading', title: '摸骨算命', description: '一位瞎眼老道拦住你，枯瘦的手指在你骨节间摸索，半晌才说：「你这命里，有两条路。」', effects: { luck: 4, intelligence: 2 }, exp: 16, minLevel: 3, weight: 1 },
  { id: 'array-trap', title: '布阵困敌', description: '你带人用简易困阵围住一头偷灵米的猪妖，阵法刚成，猪妖却一头撞在阵眼上，阵纹裂了。', effects: { intelligence: 4, agility: 2 }, exp: 16, minLevel: 3, weight: 1 },
  { id: 'pill-meet', title: '丹会献艺', description: '三年一度的丹会在州城开幕，你代表宗门出席。丹炉前，无数目光落在你手上。', effects: { intelligence: 5, charisma: 2 }, exp: 18, minLevel: 3, weight: 1 },
  { id: 'ghost-child', title: '荒村鬼童', description: '你借宿的荒村里，一个穿红肚兜的鬼童总在井边玩水。他看见你，咧嘴一笑：「大哥哥，帮我捞个月亮好不好？」', effects: { luck: 4, charisma: 2 }, exp: 16, minLevel: 3, weight: 1 },
  { id: 'herb-watch', title: '守护灵药', description: '一株千年灵芝即将成熟，你奉命看守。入夜，三条蛇妖同时现身，灵芝的香气把它们全引来了。', effects: { vitality: 4, strength: 3 }, exp: 17, minLevel: 3, weight: 1 },
  { id: 'sky-ladder', title: '天梯试炼', description: '宗门深处有一道九百九十九阶的天梯，走完者可得洗髓丹。你踏上第一阶，膝盖就微微一沉。', effects: { vitality: 4, agility: 3 }, exp: 18, minLevel: 3, weight: 1 },
  // ===== 史诗（7 个，minLevel 4/5 为主）=====
  { id: 'sect-tournament', title: '宗门大比', description: '宗门大比决赛，你站在擂台上，对面是号称「十年最强」的大师兄。台下万人屏息。', effects: { strength: 6, agility: 4 }, exp: 22, minLevel: 4, weight: 1 },
  { id: 'ancient-ruins', title: '上古遗迹', description: '一处上古遗迹在月圆之夜现世，禁制裂开一道缝隙。各大宗门蜂拥而至，都想抢在别人前面进去。', effects: { intelligence: 5, luck: 4 }, exp: 21, minLevel: 4, weight: 1 },
  { id: 'qi-tide', title: '灵气潮汐', description: '千年一遇的灵气潮汐席卷大地，凡人之躯也能感受到天地的脉动。有人借机突破，也有人被灵气冲垮。', effects: { vitality: 6, luck: 3 }, exp: 22, minLevel: 4, weight: 1 },
  { id: 'demon-seal', title: '镇压魔窟', description: '你随长老深入魔窟，镇压即将复苏的魔头。魔气如墨，你每走一步都要运功抵御。', effects: { strength: 7, vitality: 5 }, exp: 24, minLevel: 5, weight: 1 },
  { id: 'golden-core', title: '金丹凝成', description: '你迎来金丹之劫，九重雷云在头顶盘旋。成败在此一举：凝成则一步登天，失败则百年道行尽毁。', effects: { vitality: 5, intelligence: 4 }, exp: 23, minLevel: 5, weight: 1 },
  { id: 'immortal-grotto', title: '仙人洞府', description: '你寻到一位飞升仙人的洞府，府门禁制上写着「有缘者入」。洞中玉简，记载着仙人毕生的修行心得。', effects: { intelligence: 6, charisma: 3 }, exp: 23, minLevel: 5, weight: 1 },
  { id: 'chaos-beast', title: '荒古凶兽', description: '一头沉睡万年的荒古凶兽苏醒，咆哮震碎百里云层。宗门倾巢而出，你握紧法器，站在最前列。', effects: { strength: 8, vitality: 6 }, exp: 26, minLevel: 6, weight: 1 },
]
